### ISSUE TITLE
Long running tasks get HTTP 401 when using the UAA for authentication

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1002]
I'm using the UAA for authentication with the Director. The default configuration proposed at bosh.io sets the lifetime of the token to 60s.

When executing long-running tasks that take longer than the token lifetime, the token seems to expire before the task is completed. Maybe it doesn't use the refresh-token to obtain a new token?

Steps to reproduce:
* Deploy the Director using bosh-init with UAA user management as described on bosh.io
* `git clone` cf-release
* `bosh upload release releases/cf-222.yml`. This takes a long time to build the release tarball. Afterwards, the call to `/releases` fails:

```
...
Uploading release
release.tgz:   100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo|   3.4GB  10.6MB/s Time: 00:05:31
HTTP 401: Not authorized: '/releases'
```

Smaller releases work. Setting the `access_token_validity` to some higher value resolves this problem as well:
```
uaac token client get admin
uaac client update bosh_cli --access_token_validity 600
```

Seems like the time between the cli making the call and passing the token and the actual call to `/releases` is relevant.

**Comment by cppforlife** [comment]
Problem here is that because upload to nginx takes so long (for large releases), by the time token makes it into the Director it has already expired. There is no good way to fix this unless uploading is separated into another step so that it returns a token that never expires. I think for now we should just set the access token validity to some reasonable time that is greater than maximum upload time.

docs-bosh PR?

**Comment by cppforlife** [comment]
Updated https://github.com/cloudfoundry/docs-bosh/commit/8ef20b2a0dd81e0919b68fe333886949c72e07b0. 

Closing in favor of recommended solution to increase access token validity.
