### ISSUE TITLE
Bosh cck-command does not report a job error while bosh instances-command report the error

### ISSUE THREAD

**Issue by alexeivorontsov** [cloudfoundry/bosh#1066]
When I have a successful deployment for a release, I can do the following steps to demonstrate this behaviour:

````
1. bosh ssh test_vm/0
2. sudo monit stop test_job
3. exit
4. bosh cck -> shows that there are no problems
5. bosh instances -> shows 'failing' status for one the test_vm/0 box
````
Both tools should report the same thing - "failing"

**Comment by dpb587-pivotal** [comment]
The `bosh cck` command is primarily used for fixing IAAS resources (like resurrecting lost VMs or fixing disks), whereas the `bosh instances` shows details about what's running on the actual VMs.

So what you're seeing is expected behavior: all IAAS VMs are reporting so `cck` is happy, but `instances` checks the job processes and correctly notices the failure.

[bosh.io](https://bosh.io/docs/cck.html) has some more details on the usage of the `cck` command.
