### ISSUE TITLE
launch jobs in independent way with monit on bosh

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/bosh#1073]
Hi all, @mattcui 
i have a problem with making two jobs independent between each other.
I am deploying a VM with bosh and i need to start the job child only after the father job has finished.
i contacted the Monit group and they told me this feature is only supported with Monit version 5.15. 
Anyone of you has had this problem before? How did you do until Monit 5.15 to put dependencies between jobs?Thanks all

**Comment by mattcui** [comment]
@cppforlife @maximilien This requirement is from Bluemix, there are some Bosh releases/jobs we created for post-install during deployment, like creating additional accounts, applying security patches and etc. We need to have some jobs running before some other jobs during deployment, but currently, all Bosh jobs are running in parallel. We get confirmed that the latest version of monit (5.15) supports to define the dependencies between jobs, but the feature is not supported by the monit in the current Bosh release since it's a very old version (5.2.4 in 2011), I am going to submit a PR to upgrade monit first, and then we need to investigate how to define the dependencies between jobs running in a VM. Please share with us if you or anyone else have such experiences on such requirement. Thanks.

**Comment by mattcui** [comment]
@wayneszalinsky Did you follow [SERVICE DEPENDENCIES](https://mmonit.com/monit/documentation/monit.html#SERVICE-DEPENDENCIES) in monit document to have a try?

**Comment by cppforlife** [comment]
Currently bosh does not support ordered start within in a VM. For majority of cases it's best to make your apps retry connecting to dependent services when starting. Do you have more details about what you are trying to start in specified order? Regarding monit directive: we found that it's flakey at best in practice so I would not recommend using it.

**Comment by dpb587-pivotal** [comment]
Versions older than 5.15 would start a parent service but would not necessarily wait until the process was healthy before starting the child.

 > Fixed: Issue #249: Implement hard dependency between services. If a service depends on another service, it will not start until the parent service check returns no errors. For example, if Apache depends on MySQL, Monit will not start Apache until MySQL is confirmed up and running and passes all its tests. Previously, Monit would start MySQL, but not wait for MySQL to be confirmed up and running before it started Apache.
 > 
 > [changelog](https://mmonit.com/monit/changes/)

**Comment by mattcui** [comment]
After updating monit to 5.15 in the stemcell, all ruby jobs failed to start, all ruby processes were shown as zombie processes from the output of "ps -ef | grep ruby"
