### ISSUE TITLE
Changing nats password not possible

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/bosh#1140]
Using BOSH v253

We changed the property `properties.nats.password` https://github.com/cloudfoundry/bosh/blob/master/release/jobs/nats/spec#L33 and redeployed bosh with `bosh-init`. 

After that all vms are in state `unresponsive agent`. Running `bosh stop --hard` or `bosh recreate` is not possible, because bosh tries to get the state of the agent and times out `Error 450002: Timed out sending 'get_state'`. 

It would be possible by deleting all deployments or manually fixing the agent on every VM. Is there any other solution for a running system?

**Comment by bosh-ci-push-pull** [comment]
you can currently recover vms via bosh cck with recreate option.

we do have planned enhancement to bosh deploy mechanism to forcefully continue on when bosh deploy cannot communicate with a vm.

also we are planning to evaluate our usage of nats and switch to a different mechanism for communication which may completely eliminate credential rotation problem.

**Comment by achawki** [comment]
Ok thanks.

**Comment by voelzmo** [comment]
Additionally: Changing blobstore password is not possible. Shall we open something in addition or can you create an item in tracker for this @cppforlife?

**Comment by cppforlife** [comment]
@voelzmo issue marked as "planned-enhancement". i will add a story when we are getting closer to implementing this functionality.

**Comment by dcarley** [comment]
I think I understand this a bit better now..

When the NATS password is changed existing VMs continue to fetch the old NATS password from bosh-registry because it's stored in the database at `registry_instances.settings`. If you manually update that JSON and HUP `bosh-agent` then the VM will reconnect and BOSH will report it as healthy.

Would it be feasible for BOSH to rewrite all of these entries when the password changes? Would bosh-agent retry the settings service to pick these up again?

**Comment by rogeruiz** [comment]
Is this functionality any closer to being implemented? [From the CloudFoundry Slack](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1492785552950073?thread_ts=1492784585.438034&cid=C02HPPYQ2), it looks like it might be possible in the future with cloud config and CredHub.

**Comment by mogul** [comment]
Just pinging again on behalf of the cloud.gov team... Is this anywhere in your plans?

**Comment by pivotal-jamil-shamy** [comment]
@mogul in the next release of BOSH (soon), we're implementing mutual TLS for NATS communications. This will eliminate the need for passwords when connecting to the NATS server (for new stemcells).
Note: to be backwards compatible, we still support password authentication for old stemcells.
With mutual TLS, we'll have the ability to rotate certificate with potentially zero downtime.

**Comment by dcarley** [comment]
Commenting because we were confused about the changes required and I ended up here from a Google search once again..

Once you've enabled mutual TLS and disabled [`nats.allow_legacy_agents`](http://bosh.io/jobs/nats?source=github.com/cloudfoundry/bosh&version=264.7.0#p=nats.allow_legacy_agents), you can omit the following because they are no longer used:

- `nats.user` and `nats.password` properties
- `username:password@` from the `agent.mbus` URL property

But you still need a username and password in the URLs for `cloud_provider.mbus` and `cloud_provider.properties.agent.mbus` because they are used for the NATS-like interface that a VM callsback to when you are bootstrapping with `bosh-init` or `bosh create-env`.

**Comment by wickyhasan** [comment]
Hi, 
Can anyone please let me know how can I change the new NATS password into Bosh or remove the bosh registry linking to old NATS password? As I have changed the new NATS password on my Pivotal deployment but NATS old password is still linking and throwing an error:
Registrar.nats-connection-failed","log_level":2,"data":{"error":"nats: authorization violation","nats-hosts":

**Comment by pivotal-jamil-shamy** [comment]
@wickyhasan to give some context:

1. Historically, NATS communication only used username/password for authentication and authorization. Changing NATS username/password or rotating them was not possible without hitting the `unresponsive` VMs situation.
2. Starting with BOSH version `264` and linux stemcell version `3468` we added the ability for mutual TLS communication for the BOSH NATS. When communication is done through mTLS, the NATS username/password are not used for any authentication or authorization. But we still kept the ability for NATS clients to authenticate over username/password for backword compatibility reasons (For example an older stemcell).
3. If the operator knows that all the relevant components (BOSH Director and stemcells) support mTLS NATS communication, we added a configuration to the NATS server job in the BOSH release to only allow mTLS connections and drop username/password authentication.  As stated above this is the flag [`nats.allow_legacy_agents`](http://bosh.io/jobs/nats?source=github.com/cloudfoundry/bosh&version=264.7.0#p=nats.allow_legacy_agents). This flag, when set to `false`, will guarantee that the communication is over mTLS.
4. At some point we will remove that flag and only allow mTLS NATS communication. But due to the older stemcell support, this did not happen yet.

Question: What is the reason you are trying to change the NATS password ? Which version of the director and stemcells you are using ?
