### ISSUE TITLE
Change disk type from standard to io1 not working 

### ISSUE THREAD

**Issue by amulyas** [cloudfoundry/bosh#1141]
I updated the disk type from one type to another was hoping that disk copy job will kick in and it will got o another disk type but it seems nosh can not handle disk type change

**Comment by dpb587-pivotal** [comment]
You mention `io2`, but it is not a public [EBS Volume Type](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html) - double check you have the correct spelling in your manifest.

When changing `disk_pool.cloud_properties`, you should indeed receive a new disk with the data copied over. The full docs are at [bosh.io](http://bosh.io/docs/aws-cpi.html#disk-pools) if you want to double check your manifest.

Otherwise, please include the `disk_pool` configuration that you are using.

**Comment by amulyas** [comment]
@dpb587-pivotal I mean io1

**Comment by amulyas** [comment]
it might be running this in old bosh I will try to so this with latest version ad see if that works

**Comment by amulyas** [comment]
we can close this ticket for now
