### ISSUE TITLE
Remove ruby 1.9.3 for security issue

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1167]
I remember we ever talked about this, there are some ruby binary files left under /var/vcap/bosh/bin, the version of this ruby is 1.9.3, it's used to compile bosh during making stemcell, it's not useful after compilation. So it's better to add a cleanup stage or add the cleanup code in bash_clean stage:

```
echo 'Removing Ruby 1.9.3'
cd $chroot/var/vcap/bosh/bin
rm -rf aws-rb
rm -rf irb
rm -rf erb
rm -rf ruby
rm -rf rdoc
rm -rf rake
rm -rf gem
rm -rf nokogiri
rm -rf ri
rm -rf bundle
rm -rf testrb
``` 

Please let me know if you would like to accept my solution above or you have better solution to clean up it. Thanks.

**Comment by liuweichu** [comment]
Hello, I'm from a team where is running a company private cfv2 PaaS.
Actually, we are using this ruby version in our own release, in order to avoid spaghetti bash. And that is not worthy a ruby package.

I am very interested in the details of the possible security issue that caused by this vendor ruby.
Also, if it's because ruby1.9.3 is EOL, I want to know if there's a chance we update the version instead of removing the whole ruby.

**Comment by mattcui** [comment]
@liuweichu ruby 1.9.3 is very old version, there are many security issues. For BOSH, that ruby is totally no use after BOSH compilation. I believe your component shouldn't rely on that ruby, you need to install and maintain your own ruby (like CF release) if you need to use one. Thanks.

**Comment by liuweichu** [comment]
@mattcui 
Thanks for quick reply. Definitely, as you said, nothing should depend on internal bosh ruby.

By the way, as far as I know, the bosh ruby itself can only be called by root. So I'm just curious under what circumstance it would actually cause trouble.

**Comment by cppforlife** [comment]
@mattcui we are adding env variable to disable micro building as part of stemcell build process: https://www.pivotaltracker.com/story/show/114537425. this is a step towards removing it completely. we will be promoting this change soon, so i would recommend to set it when building softlayer stemcells.

@liuweichu it's strongly recommended to not use bosh's ruby because it's used *internally* (currently in stemcell building). it will be removed from stemcells completely without notice in coming months. we are not planning to upgrade it.

**Comment by liuweichu** [comment]
@cppforlife @mattcui Thanks for explanation and confirmation. Since it's official decision, we will stop using it.

**Comment by cppforlife** [comment]
Given above explanation I am going to close this issue.
