### ISSUE TITLE
Can we consider to install openssl 1.0.2 and FIPS module

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1168]
We are requested to install openssl FIPS module in the image, is it possible to upgrade openssl (from 1.0.1 to 1.0.2) and install FIPS module in Base OS or add a stage to do that? Thanks.

http://openssl.org/docs/fips.html

**Comment by cppforlife** [comment]
Currently BOSH team is waiting for an ok on FIPS compatibility work from CF foundation. Since Ubuntu does not have pre-built packages for openssl FIPS that they maintain this would be non-zero maintenance cost for the BOSH team. Once CF starts moving towards FIPS compatibility then BOSH can also take it on.

**Comment by maximilien** [comment]
Any update on this @cppforlife?
