### ISSUE TITLE
bosh vms command and unresponsive agent output

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/bosh#1192]
We use the `bosh vms` command often to check the status of our CF and get a quick overview of deployments. When bosh can talk to the agent, the command provides useful information about a machine's IP address and what job it's running. When an agent is unresponsive, though, the command simply shows `unresponsive agent` for the problem vms. This isn't useful for troubleshooting. Much more useful would be:
- Expected job
- Machine's last known IP

This would save us a great deal of time when a machine goes south via unresponsive agent.

**Comment by cppforlife** [comment]
cc @voelzmo

**Comment by voelzmo** [comment]
@cholick We have a story for returning the IP address from the DB instead of relying on what the agent returns: https://www.pivotaltracker.com/story/show/115972549

We might want to do the same things for jobs/instance groups that should be running on VMS as well, not sure what @cppforlife thinks about this.

**Comment by dpb587-pivotal** [comment]
The mentioned behavior was released in director [v259](https://github.com/cloudfoundry/bosh/releases/tag/v259). A related pull request was #1424.
