### ISSUE TITLE
line 44: undefined method `strip' for nil:NilClass

### ISSUE THREAD

**Issue by raindoctor** [cloudfoundry/bosh#1206]
While deploying cf version 231 on micro bosh stemcell version 3163, I am getting this error:

```
Director task 57
  Started preparing deployment > Preparing deployment. Done (00:00:03)

Error 100: Unable to render instance groups for deployment. Errors are:
   - Unable to render jobs for instance group 'stats_z1'. Errors are:
     - Unable to render templates for job 'metron_agent'. Errors are:
       - Error filling in template 'syslog_forwarder.conf.erb' (line 44: undefined method `strip' for nil:NilClass)
```

However, cf version 231 on micro bosh stemcell version 3160 works.

Environment: openstack, bosh dynamic network.  https://bosh.io/docs/networks.html#dynamic.

**Comment by ssurenr** [comment]
+1. I am facing this in AWS.

**Comment by allomov** [comment]
Originally, this error takes place in [loggregator template](https://github.com/cloudfoundry/loggregator/blob/cacc328e9c5962ee4afb9fca892b51d880bb462c/jobs/metron_agent/templates/syslog_forwarder.conf.erb#L24-L37).

It looks like dynamic network is not intended to provide any `ip` property to networks spec: see [this test case](https://github.com/allomov/bosh/blob/b416e8a4d608575efc1b40a7294166273c08c1fe/bosh-director/spec/unit/deployment_plan/instance_spec_spec.rb#L59-L81).

This could mean you'll need to switch to manual networks. With the latests changes to bosh project you can do it easily, because bosh director begun to provide jobs with ips automatically, so you don't need to specify `static_ips`.

**Comment by allomov** [comment]
@cppforlife @loewenstein did I get it right? should it be added to docs or fixed somehow? 

Because lots of cf-release templates use `spec.networks` to get ip addresses of the job. This fact makes it impossible to use it with `dynamic` networks.

**Comment by raindoctor** [comment]
@allomov, dynamic networks + cf-231 + any micro bosh with stemcell from 3008 to 3160 is working. The moment I upgrade to 3161, I am getting this error. So, why loggregator templates are fine with other versions of bosh?

**Comment by dpb587-pivotal** [comment]
Story: https://www.pivotaltracker.com/story/show/118348007

**Comment by chrisrana** [comment]
I am also facing same error.I am using 3232.4 with cf-231.Please help resolve this issue

**Comment by jszroberto** [comment]
Facing same issue, is this already resolved? We need to use mandatorily dynamic networks with our IaaS provider.

**Comment by kitemongerer** [comment]
Loggregator completed a [feature](https://www.pivotaltracker.com/story/show/117257489) to enable dynamic networking.

**Comment by ssurenr** [comment]
I guess this needs a fix in Bosh side as well

**Comment by dpb587-pivotal** [comment]
I believe this was fixed in bosh director [v257+](https://github.com/cloudfoundry/bosh/releases/tag/stable-3262).
