### ISSUE TITLE
Where to get the change log for base OS of stemcell?

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#1288]
We noticed that there are some changes in recent base OS of stemcells, for examples, 

In [v256](https://github.com/cloudfoundry/bosh/releases/tag/stable-3232), there installed `auditd`, but it can't work together well with our security release, since our security release installed and configured auditd by itself. We are investigating if `auditd` is installed/configured properly in the stemcell. Another change we noticed that the OS level was upgraded from Ubuntu 14.04.3 to 14.04.4. 

We need change list/log for all changes in Base OS, so that our security team could review the changes and make some adjustment if needed. Thanks.

/cc @maximilien

**Comment by cppforlife** [comment]
You should be able to find changes in the github releases. v256 release notes for example mention auditd now being installed. Each stemcell also comes with stemcell_dpkg_l.txt file (http://bosh.io/docs/build-stemcell.html#tarball-structure) which lists all packages and their versions. More details changes of course can be obtainer by using git log and filtering down to specific director (stemcell_builder for example).

Re auditd configuration, we would be interested to know how you all configure it and potentially pull in missing changes. So far we have been following STIG/CIS recommendations.

**Comment by rfreddi** [comment]
Hi, the auditd problem occurs also in a clean stemcell based on 3232.4 image.

bash -x service auditd start
++ basename service
+ VERSION='service ver. 0.91-ubuntu1'
++ basename service
+ USAGE='Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]'
+ SERVICE=
+ ACTION=
+ SERVICEDIR=/etc/init.d
+ OPTIONS=
+ '[' 2 -eq 0 ']'
+ cd /
+ '[' 2 -gt 0 ']'
+ case "${1}" in
+ '[' -z '' -a 2 -eq 1 -a auditd = --status-all ']'
+ '[' 2 -eq 2 -a start = --full-restart ']'
+ '[' -z '' ']'
+ SERVICE=auditd
+ shift
+ '[' 1 -gt 0 ']'
+ case "${1}" in
+ '[' -z auditd -a 1 -eq 1 -a start = --status-all ']'
+ '[' 1 -eq 2 -a '' = --full-restart ']'
+ '[' -z auditd ']'
+ '[' -z '' ']'
+ ACTION=start
+ shift
+ '[' 0 -gt 0 ']'
+ '[' -r /etc/init/auditd.conf ']'
+ which initctl
+ grep -q upstart
+ initctl version
+ case "${ACTION}" in
+ exec start auditd
auditd start/running, process 12118

~# ps -ef | grep 12118
root     12219  5537  0 09:53 pts/0    00:00:00 grep --color=auto 12118

Is there a particular configuration in order to enable auditd service?
Suggestions?

Thanks in advance
Remo

**Comment by dpb587-pivotal** [comment]
Related: [auditd does not start (#1305)](https://github.com/cloudfoundry/bosh/issues/1305)

**Comment by cppforlife** [comment]
Closing. Question was answered in comments above.
