### ISSUE TITLE
Stemcell upload functionality for cloud-config

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#1303]
BOSH is able to read stemcell version and URL from the deployment manifest and check if it already has it. If not, it will download it and make available for deployment.

However, if you switch to cloud-config, stemcells in the manifest are specified in the new way, which doesn't include the stemcell URL. This means that BOSH doesn't obtain stemcells itself anymore and requires operators to explicitly pre-upload the stemcells to BOSH prior to deployment.

Is there a way to get BOSH handle the stemcells like it did previously with cloud-config?

**Comment by cppforlife** [comment]
yeah, we havent decided how to solve this problem yet. given that a stemcell definition is not tied to any specific iaas or version providing a url doesnt necessarily make a lot of sense (unless i guess you are specifying a nsme instead of an os). i could be convinced adding url/sha1 to each stemcell optionally if it makes the workflow easier. currently releng team is making changes to their envs to use 2.0 features including cloud config so im expecting to receive feedback/suggestions from them about this issue as well.

**Comment by mtekel** [comment]
Being able to specify URL + SHA would be great. This would enable, for example, specifying custom built stemcells which you can host e.g. internally.
