### ISSUE TITLE
max_in_flight setting not being honoured

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1331]
I have an instance group (`runner`) with 8 instances spread across 4 AZs, and I'm overriding the `max_in_flight` for this instance group to 4 (the global is 1).  However, when I `bosh deploy` I see it's only doing 2 at a time.

[logs-and-manifest.tar.gz](https://github.com/cloudfoundry/bosh/files/344915/logs-and-manifest.tar.gz)

**Comment by dpb587-pivotal** [comment]
I believe what you're seeing is expected behaviour. Not sure if [docs](http://bosh.io/docs/deployment-manifest.html#update) need to updated to reflect this?

When updating an instance group, director does [one AZ at a time](https://github.com/cloudfoundry/bosh/blob/28001bdcbf4e6d31ab153139f54b8047de71deb6/bosh-director/lib/bosh/director/job_updater.rb#L58) and waits for that AZ to finish before moving to the next. So `max_in_flight` is effectively `max(instances-in-az, coalesce(instance_group.update.max_in_flight, deployment.update.max_in_flight))`; in your case 2.

**Comment by cppforlife** [comment]
@Amit-PivotalLabs not sure if you are proposing to disregard AZ isolation. this somewhat follows the current behavior with max_in_flight + z1/zx splits.

**Comment by cppforlife** [comment]
Closing. Currently works as desired.
