### ISSUE TITLE
Unable to use compiled_package_cache with bucket outside us-east-1

### ISSUE THREAD

**Issue by aristotelesneto** [cloudfoundry/bosh#1353]
It appears that the s3cli blobstore client expects to see options[region], but region is not passed in via the spec to the director, to be used in the compiled_package_cache.

**Comment by aristotelesneto** [comment]
Sorry, my bad.

Looks like it uses a property outside compiled_package_cache block, which was unexpected:
https://github.com/cloudfoundry/bosh/blob/master/release/jobs/director/templates/director.yml.erb.erb#L216

**Comment by dpb587-pivotal** [comment]
@cppforlife, this seems like poor UX. Would we be willing to accept a PR for a new property with something like `p('compiled_package_cache.options.region', p('blobstore.s3_region', nil))` for sane behavior but maintaining existing unexpectedness. Since compiled package cache could be a separate bucket, it seems like region should be independently configurable.

@aristotelesneto, nice investigation.

**Comment by cppforlife** [comment]
i think this would make sense.

**Comment by sbaxter** [comment]
+1
