### ISSUE TITLE
Bosh needs to deal properly with unspecified availability_zone

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh#1366]
Bosh recently lost a VM and did not resurrect it, nor would a `bosh deploy` or `bosh cck` indicate any issues.  However on further inspection, without an `resource_pool.availability_zone` property the HM cannot find a solution to resurrect.

```
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Director task 16544
  Started scanning 1 vms
  Started scanning 1 vms > Checking VM states. Done (00:00:10)
  Started scanning 1 vms > 0 OK, 1 unresponsive, 0 missing, 0 unbound. Done (00:00:00)
     Done scanning 1 vms (00:00:10)

  Started applying problem resolutions > Problem (unresponsive_agent 186) is no longer valid: VM '' is no longer in the database (unresponsive_agent 186): no resolution. Failed: Cannot find 'recreate_vm' resolution for 'Bosh::Director::ProblemHandlers::InvalidProblem' (00:00:00)

Error 100: Error resolving problem '268': Cannot find 'recreate_vm' resolution for 'Bosh::Director::ProblemHandlers::InvalidProblem'

```

**Comment by cppforlife** [comment]
@sharms in one of the aws cpi releases we have removed default_availability_zone as a configuration in favor of setting it explicitly in the resource pool (as you pointed out above). without updating the deployments with manifests that specify availability_zone the cpi will not be able to recreate machines (since definition is missing availability_zone). can you confirm that issue goes away once cloud properties are updated to include availability_zone?

**Comment by sharms** [comment]
This issue went away and VMs appeared restored after adding availability_zone

**Comment by cppforlife** [comment]
Thanks for confirmation. Im not sure what the Director can do to prevent this scenario since it's would have to know more about CPI changes which is something we would want to avoid. We are also making sure that CPIs are a bit more specific about VM locality instead of having some kind of a default.
