### ISSUE TITLE
s3cli doesn't automatically pick signing algorithm based on region anymore

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#1373]
When selecting `region: eu-central-1` for the Director blobstore, the previous `s3_blobstore_client` used to [automatically select v4 signing](https://github.com/cloudfoundry/bosh/blob/master/blobstore_client/lib/blobstore_client/s3_blobstore_client.rb#L147-L157)
However, since the move to s3cli, this doesn't work anymore, [it just gets the signing version from the config](https://github.com/cloudfoundry/bosh/blob/master/blobstore_client/lib/blobstore_client/s3cli_blobstore_client.rb#L42). I would have to specify the signing version explicitly in the manifest. Can I get the old behavior back?

PS: why is the old s3_blobstore_cli still in the code, if the s3cli is the default? :)

**Comment by voelzmo** [comment]
I guess I found the problem: setting `region` doesn't help, setting `host` to `s3.eu-central-1.amazonaws.com` instead did the trick.

**Comment by ljfranklin** [comment]
@voelzmo if you don't specify a host, we should default to v4: https://github.com/pivotal-golang/s3cli/blob/c2681be1e08d6e6ce2a6aca796fecc597df2ebd9/config/config.go#L123.

Were you explicitly setting the host to something that is not in this list: https://github.com/pivotal-golang/s3cli/blob/c2681be1e08d6e6ce2a6aca796fecc597df2ebd9/config/endpoints.go?

**Comment by voelzmo** [comment]
@ljfranklin I still had `s3.amazonaws.com` as `host` because I forgot to remove it. Although I specified `region: eu-central-1` explicitly, it seems like s3cli selected `us-east-1` as region, not even hinting me towards my problem. I guess that could have been a bit more verbose on what happened magically.

**Comment by ljfranklin** [comment]
@voelzmo looks like [this line](https://github.com/pivotal-golang/s3cli/blob/c2681be1e08d6e6ce2a6aca796fecc597df2ebd9/config/config.go#L113) is the problem. We shouldn't override the region if it was already set. The overly magic decision making was intentional as we felt it would be too confusing for users to specify AWS signing info in a director manifest.

Story to fix region clobbering is [here](https://www.pivotaltracker.com/story/show/127485941), thanks for the heads up!

**Comment by voelzmo** [comment]
Thanks @ljfranklin. As a comment to the patch: maybe you also want to check if the user-provided region matches the calculated one and error out if there's a mismatch?

**Comment by ljfranklin** [comment]
@voelzmo The AWS API returns back a reasonable enough error if the region and hostname don't match. We've had several stories around removing validation from the CPI because AWS added some new feature and our checks are too restrictive. We try to let AWS perform the validation if we can. Luckily the AWS SDK + API do a decent job of returning readable errors, most of the time :)

PR to bump s3cli is [here](https://github.com/cloudfoundry/bosh/pull/1376), this can be closed out once that PR is merged.

**Comment by dpb587-pivotal** [comment]
Merged #1376 with the s3cli fix, so this should be in the next release. Closing per above comment.
