### ISSUE TITLE
bosh ssh is very slow

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/bosh#1400]
`bosh ssh` is very slow compared to direct ssh access (even with intraDC latencies)

Very unscientific benchmark:
running `time bosh ssh cc/0 exit`: 
real    0m1.921s
real    0m2.855s
real    0m3.844s
real    0m2.820s
real    0m2.841s
real    0m5.849s

running `time runsrv cc/0 exit` (note: `runsrv` it's just a custom wrapper around the `ssh` command)
real    0m0.119s
real    0m0.120s
real    0m0.079s
real    0m0.081s
real    0m0.079s
real    0m0.075s

I agree that `bosh ssh` does much more than just opening the ssh connection, but the overhead it imposes makes it hard to justify. When doing troubleshooting the latency makes it pretty hard to be effective. Any chance it can be sped up?

BOSH 1.3232.0

**Comment by cppforlife** [comment]
@CAFxX Currently there is a roundtrip between CLI and the Director (to authorize SSH access) and between the Director and the Agent (to configure SSH pubkey). It's a bit hard to compete with plain SSH connection since keys are already pre-provisioned vs BOSH configuring the VM with dynamic keys every time you initiate SSH session. There are a few opportunities for optimization at all levels: go cli (upcoming; currently in alpha1) to speed up ruby startup time, cutting out Agent round trip if all keys are already preconfigured, and responding from Director API immediately (instead of from the worker) assuming that keys are preconfigured. With all that we would just end up with a single CLI to Director roundtrip and actual SSH connection. Not sure how you feel about preconfigured keys on all machines?

**Comment by CAFxX** [comment]
Here's a random idea (not mine, borrowed from how bitcoin wallets work): pre-provision a pool of single-use keys for each VM. Use one of the keys from the pool when connecting; when the connection ends the key is deleted and a new one generated and added to the pool.

**Comment by cppforlife** [comment]
@CAFxX i could see us switching from dynamically generated keys to something more pre-provisioned for the sake of a speedup. this could even help with the case when agent is unresponsive for some reason and you still want to get to the box.

**Comment by Freyert** [comment]
The problem isn't really that you have to generate keys, the problem is that you have to do it _every_ time.

Why not just have BOSH integrate with `ssh-agent`? That way users can leverage whatever SSH/SCP tooling they prefer and it would allow integrating BOSH with tools like Ansible. Plus SSH and SCP are _enormously_ powerful tools with loads of options and uses that BOSH SSH/SCP will never come close to implementing all of. Also, it would be a waste of time and effort to do that.

Instead BOSH could just focus on sanely/safely handling key and socket creation/termination. You could set TTL for socket/keys through the command and then plug whatever tool you wanted into the socket.

**Comment by CAFxX** [comment]
> And just as an FYI, most teams that I've spoken with who have created their own releases include steps to either create an SSH user, or change the VCAP password so that they can SSH natively.
> 
> This is Shadow Ops, and points to the fact that BOSH ssh/scp instead of being features are detriments. Something entirely different may be called for.

Yup that's [we have also done](https://github.com/rakutentech/dotfiles-boshrelease/blob/769e98fbebe5a57af4f6177d187c9104d9023db5/jobs/shrc/spec#L41-L46).
