### ISSUE TITLE
Feature: Add the capability to compile all packages in use on a given Stemcell

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/bosh#1451]
When you upload a new Stemcell most deployments will recompile their Packages when you explicitly tell BOSH to deploy. Due to the fact that some Releases, like CF have a high number of Packages the compilation will take a while. If you have multiple Deployments, and you want to update sequentially, then you waste a lot of time just waiting for the compiles before the real update begins. 
A way to mitigate that would be the option to tell bosh to compile or recompile all packages that are in use on a given Stemcell that was uploaded to BOSH already, example:

bosh compile packages <stemcell> [version] [release]

Advantages would be:
- Shorter Maintenance windows, as it is then possible to do the 2-4 Hours of compilation in advance before the Nodes are updated in a Production Environment.
- Less waiting for the start of node updates on a deployment, which has packages that take a long time to compile (CF, MongoDB)

In terms of User stories I would suggest these:
As a Cloud Operator, I want the ability to compile all Packages, which are in use at once. This will enable me to shorten Maintenance Windows and Deployments after a Stemcell upgrade.

**Comment by d** [comment]
Hi Sven,
I think you're already able to do this, by `bosh export release`:

0. Let's assume you have a staging environment, because hey, you're serious about your production
0. Your staging deployment uses the exact same stemcell and release versions as your production.
0. Before the "next big" deploy to production, upgrade your staging environment
0. Of course you'll run tests
0. `bosh export release`
0. Now take that output and upload it to your production BOSH, things will go way faster :)

c.f. https://bosh.io/docs/compiled-releases.html

I hope this helps.

**Comment by dpb587-pivotal** [comment]
As @d suggested, `bosh export release` is a good solution. Another option you could consider is configuring a common [compiled package cache](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p=compiled_package_cache) between your environments.
