### ISSUE TITLE
Documentation on how to create OpenStack Light Stemcell

### ISSUE THREAD

**Issue by xyloman** [cloudfoundry/bosh#1464]
We have a deployment of OpenStack where glance image uploads are disallowed.  I have been struggling on how to create a [light stemcell tarball](https://bosh.io/docs/build-stemcell.html#light-stemcells) that can be leveraged by CPI in OpenStack.  Any assistance on the construction of the cloud_properties would be greatly appreciated.  I will also help test out the steps so that they can be added to the documentation under light stemcell + openstack on bosh.io.

**Comment by voelzmo** [comment]
@xyloman Where would your full stemcell come from in this case?
On AWS, we have light and full stemcells, because:
 * there is a global image store where people can get public images from
 * you can import images to use into your own account by referencing those global images
 * you can then start a VM with the image in your account

In OpenStack you can only start a VM referencing an image from the glance image store. So, whatever you do, somebody has to upload the stemcell into the glance store. Would this be taken care of by your IT operations people? Is this just something which is not allowed for regular users? Please note that stemcells might be updated very frequently, i.e. at least once per week. I don't know if the setup you're working in is a good fit for that.

Out of curiosity: Are you using a publicly available OpenStack, or is this some on-premise installation by your company?

**Comment by xyloman** [comment]
Great questions and thanks for the response. This is an on premise installation of openstack. The Operations team for openstack where going to upload the image manually during the proof of concept phase. After which time we hope to leverage the bodh automation for updating the stem cells. The long term goal is to go with the setup similar to what is documented. However, I could still see a need to reference an image that might have already been uploaded wouldn't we still need the light stemcell in that case?

**Comment by voelzmo** [comment]
In OpenStack you reference images by their UUID when booting a VM. Therefore, if the image is public, you don't need a light stemcell, you just include the image's UUID in your deployment manifest. A light stemcell can't help you there, OpenStack doesn't have the concept to copy over images from somewhere else.

Please note that bosh-init doesn't support using an existing stemcell, on the first run it will always need to upload one.

**Comment by cppforlife** [comment]
> you just include the image's UUID in your deployment manifest

not sure how you would do that. wouldnt you want to wrap that into a light stemcell and have cpi just use that uuid?

**Comment by voelzmo** [comment]
Hm, I see. So after giving this some thought: If you want to re-use existing public images in your OpenStack instead of uploading your own, light stemcells sound like a possible option.

However, you would have to produce those yourself – in contrast to AWS this is not something we can provide on bosh.io, as the UUIDs would be different on every installation.

@cppforlife How would you imagine those light stemcells being produced? Some bosh command to create it from a stemcell UUID which is later uploaded to the Director with `bosh upload-stemcell`? Could we teach `upload-stemcell` to take a UUID instead? I guess we'd have to extract the metadata which is normally present in a `stemcell.MF` from the IaaS then?

**Comment by cppforlife** [comment]
@voelzmo i think it makes sense to add a short script to bosh-openstack-cpi-release repo that will take whatever openstack specific info (uuid?) is necessary and produce a stemcell tarball for it. whoever needs to create light stemcell can just clone the git repo and run the script.

**Comment by voelzmo** [comment]
@cppforlife that script will need the same configuration as the CPI, as it talks to OpenStack to fetch image metadata. Certainly doable, but users would now need to clone the OpenStack CPI repo just for a small script...

**Comment by voelzmo** [comment]
What do you think about taking https://github.com/cloudfoundry-incubator/aws-light-stemcell-builder and making an openstack-light-stemcell-builder which takes your OpenStack credentials and the UUID of the image to produce a light stemcell?

**Comment by cppforlife** [comment]
why does it need to talk to openstack. user just need to provide uuid. i think git clone and bash script is enough but it is your call.

**Comment by voelzmo** [comment]
created epic: https://www.pivotaltracker.com/epic/show/3095067

**Comment by voelzmo** [comment]
[OpenStack CPI release v28](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/releases/tag/v28) has support for light stemcells. We also include a [script](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/scripts/create_light_stemcell) to create a light stemcell archive. PR for  documentation for bosh.io is currently open: https://github.com/cloudfoundry/docs-bosh/pull/249
