### ISSUE TITLE
How to get IP of VM in release job template

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#1476]
Many Cloud Foundry releases have jobs with templates that do something like this:

```
<%=
def discover_external_ip
  networks = spec.networks.marshal_dump

  _, network = networks.find do |_name, network_spec|
    network_spec.default
  end

  if !network
    _, network = networks.first
  end

  if !network
    raise "Could not determine IP via network spec: #{networks}"
  end

  network.ip
end

{
  foo: discover_external_ip, 
  ...,
}.to_json
%>
```

We'd like to use something like `spec.address` but there have been many problems with this, e.g. not returning an IP for certain network types, doing something funny when having multiple dynamic networks, etc.

However, we don't really understand how our own ERB works either.  What is `network_spec.default`, and under what circumstances would it be a truthy value?   Under what cases could the `raise` actually happen?  It would appear to me that `spec.networks.marshal_dump` would have to be an empty array for this to happen, is that even possible?  Or is that line just being super defensive?

I suspect `spec.networks.marshal_dump` is a hash representation of the networks associated with the instance group, where the keys are network names, and the values are some representation of a network spec.  Is that correct?  If so there is no order guaranteed, so `_, network = networks.first` will set `network` to just some network.

Finally, most importantly, what is the logic that determines the value of `network.ip`?  How does it depend on the CPI?  How does it depend on the network type?  How does it depend on whether or not static IPs have been specified for the instance group?

/cc @zankich @christianang @cppforlife @tylerschultz

**Comment by tylerschultz** [comment]
Didn’t write the code, but here’s reasonable guesses based on what it’s doing...

```ruby
<%=
def discover_external_ip
  # convert our OpenStruct into something reliable to iterate over
  networks = spec.networks.marshal_dump

  # find the first network which is marked as “default”
  # default here is an array which may contain `dns` and/or `gateway`
  # the values for `default` are documented in http://bosh.io/docs/networks.html#multi-homed
  _, network = networks.find do |_name, network_spec|
    # director always fills in `default` to be at least an empty array
    # which is truthy... so really the first network is always going to be returned
    # and since this networks was a hash, ordering is not guaranteed

    # This property is only helpful if you care to know which ip is desired, 
    # the ip which is the gateway or the ip that is to be used for dns
    # e.g. network_spec.default.include?(‘gateway’)
    network_spec.default
  end

  # if there was only a single network, the user didn’t set `default`, so pick the first one
  # nowadays, the director fills in `default` with both to avoid this sort of extra check
  # I think it was introduced in 257.x+
  if !network
    _, network = networks.first
  end

  # this should never happen... there will always be a network
  if !network
    raise "Could not determine IP via network spec: #{networks}"
  end

  # hooray. here’s our network’s IP
  network.ip
end
%>
```

There is a special case of dynamic networks where IPs are not known when we first render templates. In this case, director intentionally fills in network-like values so templates don’t know a difference (i.e. `127.0.0.1`). The templates rendered with these values are not installed because after the dynamic VM comes up, we update the spec’s IPs and re-render the templates with new values, and those results are what are sent to the VM.

The value of `network.ip` is whatever value the director/IaaS have assigned the network interface. The templates shouldn’t really care where it comes from, but it will always have an IP value that the templates can use. It’s not possible to derive whether the network was dynamic or manual - that’s not something releases should care about.

It’s also probably worth mentioning that there’s a new (not yet released) default of `addressable` ([story](https://www.pivotaltracker.com/story/show/127134831/)) which may be of interest to releases which are trying to broadcast their bound IPs for a service. It’s particularly geared for links.

/cc @dpb587-pivotal

**Comment by Amit-PivotalLabs** [comment]
Given what you said, seems like the above code would be equivalent to

```
_, network = spec.networks.marshal_dump.first
network.ip
```

In fact, is `spec.networks` an array of things which each have a `.ip` method which is guaranteed to return an IP?  If so, can the above be replaced with:

```
spec.networks.first.ip
```

----

We'll look into the `addressable` stuff when it comes out.

----

Something awkward must be going on with the original code.  I suspect some jobs would behave oddly if their discovered external IP changed between updates.  So is the above perhaps relying on some implicit determinism in the order of `spec.networks.marshal_dump`?  I.e. perhaps Ruby enumerates the hash deterministically, and we're just getting lucky...

**Comment by Amit-PivotalLabs** [comment]
@tylerschultz any thoughts on those questions above?  No rush, but it would be good to know because this could lead to cleanup in a ton of releases out there, especially applicable to consul-release and etcd-release. The complexity of the current logic has made debugging some recent issues hard. /cc @christianang

**Comment by cppforlife** [comment]
@Amit-PivotalLabs bosh release 258 brings `spec.ip` which returns ipv4 for network marked as default for gateway. or if operator want to select a different network they can explicitly mark it as addressable.

```
networks:
- name: blah
  default: [addressable] # <---- spec.ip will return blah's ip for this machine
- name: other
  default: [dns, gateway]
```

spec.networks is a hash so there is no order. what you typically want is a network that is marked as default for gateway. snippet in the first comment isnt entirely correct either since you may have networks that are only default for either dns or gateway, but that's pretty rare.

ultimately switching to spec.ip would remove all of the ambiguity out of releases and put operator in control of which ip is given to the release. 

keep in mind that spec.ip is only available for current instance's ip. there is no `.ip` accessor on links' instances, only `.address`.

**Comment by cppforlife** [comment]
@Amit-PivotalLabs im going to call this ticket closed given addition of `spec.ip`.
