### ISSUE TITLE
Post-deploy false by default?

### ISSUE THREAD

**Issue by lnguyen** [cloudfoundry/bosh#1486]
Is there a reason why post-deploy scripts are disabled by default?

**Comment by lnguyen** [comment]
Mind if we turn it on by default now?

On Fri, Oct 21, 2016 at 1:51 PM Dmitriy Kalinin

<
mailto:Dmitriy Kalinin <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/lnguyen
most of the larger features are not enabled by default as they get rolled out. this fell into that category.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/cloudfoundry/bosh/issues/1486#issuecomment-255433233
, or

**Comment by cppforlife** [comment]
@lnguyen we could switch it on in the next few releases.

**Comment by mfine30** [comment]
@lnguyen could you provide more context on your use case for having it on by default? Could you share which releases you're relying on for this functionality?

**Comment by h4xnoodle** [comment]
I think this should be enabled by default @mfine30 since there isn't a reason for it not to be. 

To opt into this lifecycle event you must do two things: script and enable the flag. If it were on by default, omitting the script would be the same as the default being disabled.

Additionally, [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) ships with `enable_post_deploy: true`.

**Comment by mrosecrance** [comment]
It defaults to true now. https://www.pivotaltracker.com/story/show/161970878
