### ISSUE TITLE
Export job index in hm graphite plugin

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry/bosh#1490]
The hm graphite plugin doesn't export the heartbeat. Would you accept a PR adding the index to this metric exporter?
https://github.com/cloudfoundry/bosh/blob/cc49a8ee67434b3ac89deae81724403283c51bfa/bosh-monitor/lib/bosh/monitor/plugins/graphite.rb#L49

**Comment by dpb587-pivotal** [comment]
We're switching away from using indices in favor of IDs, so the [change](https://github.com/cloudfoundry/bosh/commit/63a1348f2958aaa73ddc54b998165c38e80bd793) was intentional. Hopefully you can start transitioning your tooling to be ID-based? If you have any interesting stories or issues on that migration path, it would be interesting to hear about them.

**Comment by bodymindarts** [comment]
Okay understood. That will do for now.
