### ISSUE TITLE
can't specify azs in single-subnet dynamic networks

### ISSUE THREAD

**Issue by craigfurman** [cloudfoundry/bosh#1502]
In cloud config, when using the single-az syntax (no subnets array) for a dynamic network, you can't specify an "azs" array.

We are using GCP, where subnetworks span all AZs in a region. This affects our ability to explicitly specify which AZs an instance group should be balanced across.

Craig & @camelpunch

**Comment by cppforlife** [comment]
you should switch to using multi az syntax with a single subnet.

networks:
- name: net
  type: dynamic
  subnets:
  - azs: [z1,z2]
     cloud_properties: {...}

**Comment by camelpunch** [comment]
We have already done this as a workaround. How would we specify AZs that an instance group should be balanced across using the single subnet syntax?

**Comment by cppforlife** [comment]
@camelpunch there are two different az configurations: 

1. on a network (via subnets): specifies what azs bosh network spans
2. on an instance group: specifies where group's instances should go into

single subnet syntax will be eventually deprecated since it's covered by the multi subnet syntax (with single subnet). that will also make it more consistent with manual networks.

**Comment by cppforlife** [comment]
Closing. Feel free to reopen if answer above didnt answer the question.
