### ISSUE TITLE
Multi-cpi: Cannot upload stemcell for the 'default' cpi, when cpi-config has been uploaded

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh#1542]
## Steps to reproduce:
- upload cpi config
- upload stemcell (uploads images for all CPIs configured, but not for the 'default' CPI)
- deploy a release not using cloud config (and cpi config)

=> `Error: Required stemcell {"name"=>"bosh-openstack-kvm-ubuntu-trusty-go_agent", "version"=>"3312.9"} not found for default cpi, please upload again`

The cli also does not offer a way to upload the stemcell explicitly for the 'default' CPI.

Expectation here is, that this should be possible to be able to use cpi config and classical manifests, similar to the cloud config scenario.

**Comment by cppforlife** [comment]
@friegger that's somewhat purposeful so that we start moving people toward cpi config if they opt into it. eventually i see us moving away entirely from default configuration on the cpi.

**Comment by Kiemes** [comment]
This could be a solution https://github.com/cloudfoundry/bosh/tree/multi-cpi-backwards-compatibility. @cppforlife what do you think?

There is one drawback. If the user decides to put the `default cpi` into the `cpi-config` as well, stemcells are uploaded twice to the same project. 

> eventually i see us moving away entirely from default configuration on the cpi.

With this you cannot get rid of the `default cpi`. This would require special treatment like a `consider_default_cpi` flag. The name `default cpi` might be reconsidered then.

**Comment by jfmyers9** [comment]
As discussed, this change in behavior was somewhat intentional.

Going forward, we have introduced the `migrated_from` directive in the CPI config so that assets associated with the default CPI `""` can be associated with a CPI specified in the CPI config. An example of this looks like:

```
- name: cpi
  migrated_from:
  - name: ""
```

As of now, we don't expect CPI configs to work with v1 manifests.

We are going to close this issue, feel free to reopen if you have more concerns.

Best,

@jfmyers9 && @belinda-liu, CF BOSH
