### ISSUE TITLE
A BOSH deployment should include either the node jobs: or instance_groups:

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/bosh#1543]
Greetings.

Today I migrated a deployment, and replaced jobs with instance_groups. Due to a typo I wrote instance-groups, leading to all vms being deleted. I expected the Director to either warn me visibly or outright fail on deployment start, because I did not specify what should be deployed. I am aware that some people use deployments with empty job lists to compile releases, which would then have to insert something like `instance_groups: []` should the node become required. Which is a rather small change, compared to the risk of accidential deployment of nothing.

**Comment by cppforlife** [comment]
@schmidtsv we are planning to make sure director complains on any unknown key specified in the manifest, which i think will cover typo scenario in your case. wdyt? btw don't forget about http://bosh.io/docs/persistent-disks.html#orphaned-disks so that you can recover your deployment's persistent data.

**Comment by schmidtsv** [comment]
Revcovering was no issue, as this was an ephemeral deployment (meaning all data was stored outside of it). I would like to point out, that, according to the Documentation for v1 manifests (https://bosh.io/docs/deployment-manifest.html#jobs) and v2 manifests  9https://bosh.io/docs/manifest-v2.html#instance-groups) those blocks are marked as required. Therefore a user should be able to expect, that the Director fails if those blocks are missing. Unknown keys are also a nice idea for a feature, so +1 for that.

**Comment by mfine30** [comment]
This is along the lines of manifest strictness/validation (related [note](https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/manifest-strictness.md)). This is kind of a more general case of https://github.com/cloudfoundry/bosh/issues/1686, but since this isn't on our short-term roadmap, I'm going to close this. Let's consolidate further discussion around validation in that other issue.
