### ISSUE TITLE
Api requests redirect

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/bosh#1559]
When request /deployments/{name}/vms?format=full ,it will redirect /tasks/{id},
I use same  same authentication header ,and edit Location value ,for 192.168.12.11 to 192.168.12.11:25555
response status 302 Moved Temporarily 
redirect GET https://192.168.12.11:25555/tasks/6547 HTTP/1.1
but when request /deployments/{name}/vms , it is successful

**Comment by allomov** [comment]
This is expected behaviour, if you take a look on [the code](https://github.com/cloudfoundry/bosh/blob/develop/src/bosh-director/lib/bosh/director/api/controllers/deployments_controller.rb#L237). `format=full` triggers [tasks](https://github.com/cloudfoundry/bosh/blob/develop/src/bosh-director/lib/bosh/director/jobs/vm_state.rb#L34) that gathers actual information from all instances in the deployment. This can require too much time to wait.

**Comment by geekyzk** [comment]
@allomov thanks,i know ,  Is there any way to get all the data?

**Comment by allomov** [comment]
You can fetch the result by making the following request:
```
curl -v -s -k -H "Authorization: bearer $UAA_TOKEN" "https://$BOSH_HOST:25555/tasks/<task-id>/output?type=result"
```
Also you can simply run bosh-cli command:
```
bosh task <task-id> --result
```

**Comment by geekyzk** [comment]
thanks,successfully solved
