### ISSUE TITLE
/deployments endpoint does not return stemcells' operating_system

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/bosh#1626]
The JSON returned from `/deployments` has [].stemcells with "name" and "version" keys, but I would expect to see "operating_system" like I do with `/stemcells`. Without that, I need to cross-reference my deployment's stemcells with the director's stemcells to find the actual operating_system, which is necessary to perform an `export-release`.

**Comment by wendorf** [comment]
It would also be great if, once this is fixed, the bosh-cli also populates osName when fetching deployment stemcells.

**Comment by cppforlife** [comment]
@wendorf that works as desired since we only return "id" (for stemcells it's name+version) of referenced objects in api responses. to solve this problem client library should fetch missing info lazily from /stemcells endpoint which provides complete stemcell object descriptions. an example of Deployment object doing it: https://github.com/cloudfoundry/bosh-cli/blob/master/director/deployment.go#L51

cc @drich10
