### ISSUE TITLE
Building a CPI for a system that doesn't support disks as independent entities

### ISSUE THREAD

**Issue by tintoy** [cloudfoundry/bosh#1656]
Hi.

I've been looking into implementing a CPI, but the system that I'm targeting has no concept of disks that exist independently of VMs. You can add a new disk to a VM, and you can remove a disk from a VM, but once it's removed the data is gone.

From what I can tell, BOSH assumes that any provider it uses has this capability. Is what I'm trying to do even possible?

Happy to provide additional details if needed.

Thanks,

Adam.

**Comment by cunnie** [comment]
Hi tintoy,

If I understand you correctly, what you're saying is that all the disks will be ephemeral — your CPI won't have a concept of a persistent disk.

I think you might be able to get away with it by simply no-op'ing the [disk management api](https://bosh.io/docs/cpi-api-v1.html) calls (i.e. create_disk, delete_disk, has_disk, attach_disk, detach_disk, get_disk). And also by making sure no manifests you deploy make use of a persistent disk. It may make it impossible to deploy a BOSH director without some underhanded cleverness, but you could probably deploy all your VMs with the BOSH CLI v2.

Deploying something sophisticated like Cloud Foundry or databases would probably be out of the question (databases tend to depend on persistent data & don't want to lose them due to a re-deploy), but for simple services (e.g. DNS secondary nameservers), not have a persistent disk is fine.

**Comment by tintoy** [comment]
Thanks @cunnie - that's exactly the kind of info I was after! :)

**Comment by cppforlife** [comment]
@tintoy do you mind sharing which provider you are trying to integrate with? for production workloads we typically expect that this is possible since moving data around for data services is very expensive (scp, etc.).

as @cunnie mentioned above if you are not using persistent disk functionality in your manifest these CPI methods wont be called. alternatively you might have some luck implementing data movement yourself (within the CPI).

**Comment by tintoy** [comment]
Hi - sorry for the late reply; I missed the notification email.

I work for Dimension Data, and our cloud API doesn't currently expose virtual disks as stand-alone devices. At this stage, I think the CPI option is a non-starter since the client in question wants to run Cloud Foundry. We'll therefore probably host it for them on the underlying (VMWare / Hyper-V) infrastructure. If we do add persistent disk support, I'd love to revisit this and will probably hit you up for some advice when that happens :)

**Comment by dpb587-pivotal** [comment]
Sounds like the questions have been answered, but please feel free to join us in [cloudfoundry#bosh](http://slack.cloudfoundry.org) or create new issues if you revisit this and have more questions!

**Comment by tintoy** [comment]
Thanks, @dpb587-pivotal :)
