### ISSUE TITLE
bosh-openstack-stemcell-3363.20-agent user and password issue

### ISSUE THREAD

**Issue by bxlkm** [cloudfoundry/bosh#1667]
After the completion of the openstack VMS installation bosh, bosh-cli SSH into the vms host， but /var/vcap/... are root permissions can not operate, sudo command requires a password,。
ask for help, thanks.

**Comment by cppforlife** [comment]
If you need to add a user to a VM you can colocate user_add job: https://bosh.io/jobs/user_add?source=github.com/cloudfoundry/os-conf-release&version=12. that's what bosh-deployment does for director vm access: https://github.com/cloudfoundry/bosh-deployment/blob/master/jumpbox-user.yml. otherwise for vms managed by the director you can of course use bosh ssh that will create a user on the fly.

**Comment by bxlkm** [comment]
thanks.
