### ISSUE TITLE
Bosh stemcell upgrade and patches

### ISSUE THREAD

**Issue by jaikanthm** [cloudfoundry/bosh#1682]
Hi Guys, 

I have a question with respect to upgrading stemcells using BOSH. When doing a stemcell upgrade or when patching does it have any impact with respect to uptime of the respective instances. Can a zero downtime be achieved ?

**Comment by dpb587-pivotal** [comment]
Hi - yes, a deployment can achieve zero downtime. BOSH provides the primitives to make it possible, but how you go about that depends greatly on the software, environment, and service requirements.

For example, the Cloud Foundry / [cf-release](https://github.com/cloudfoundry/cf-release) can be deployed on a single VM... but a single VM is not H/A. Instead, you would potentially deploy multiple VMs of each component in different AZs.

From the BOSH side of things, there are two basic types of updates - one which will completely replace the VM (e.g. stemcell upgrade), and one which will stop/reconfigure/start process on existing VMs (e.g. patching configuration). In both cases, processes are temporarily stopped, so, as a deployment operator, you would ensure the service has other VMs picking up the slack. BOSH or not, a service should be able to handle the disappearance of a VM due to hardware failure (and in BOSH's case, it can automatically bring that VM back).

When managing large numbers of VMs or VMs across multiple AZs, you can control how many VMs are being updated at a time (e.g. if you have 10 app servers per AZ, you could configure it to ensure there's at least 5 servers running at a time).

**Comment by jaikanthm** [comment]
Hi @dpb587 

Thanks a ton for the detailed reply. That clarified the question and threw the right amount of light. 

Thanks again
