### ISSUE TITLE
About timed out pinging after 600s error.

### ISSUE THREAD

**Issue by zhoutiekui** [cloudfoundry/bosh#1703]
I encoutner the error several times. but I didn't really get the actuall logic about this error.

First, I found the error codes of the wait_until_ready function as below.  and the exception is caused by the "ping" method failure. however, i didn't know what the ping action definition ? where is the ping definition code? 

    `def wait_until_ready(deadline = 600)
      old_timeout = @timeout
      @timeout = 1.0
      @deadline = Time.now.to_i + deadline

      begin
        Config.job_cancelled?
        ping
      rescue TaskCancelled => e
        @logger.debug('Task was cancelled. Stop waiting response from vm')
        raise e
      rescue RpcTimeout
        retry if @deadline - Time.now.to_i > 0
        raise RpcTimeout, "Timed out pinging to #{@client_id} after #{deadline} seconds"
      rescue RpcRemoteException => e
        retry if e.message =~ /^restarting agent/ && @deadline - Time.now.to_i > 0
        raise e
      ensure
        @timeout = old_timeout
      end
    end`

Second, I had encountered the problem caused by the registry instance_manager.rb read_settings function failure. however, what's the relationship between the "ping" method and read_settings? 

```
`
def read_settings(instance_id, remote_ip = nil)
      check_instance_ips(remote_ip, instance_id) if remote_ip

      get_instance(instance_id).settings
    end`
```
I really want to get known the logic, anybody who can explain this, many thanks.

**Comment by dpb587-pivotal** [comment]
Hi! Generally speaking, when you encounter this error it means there's a communication problem somewhere between director and agent. There are a few tips for resolving [here](https://bosh.io/docs/tips.html#unreachable-agent), but typically it's due to network misconfiguration and firewall rules.

Internally, director is sending a `ping` message expecting the agent to be connected and listening to NATS. This is how director knows the agent is up and ready, because, once it is connected, the agent will reply back with a simple `pong`-like message. Director takes that as confirmation and will continue the provisioning process.

The registry helps provide some live VM settings for some IaaSes that the agent needs when running. I'm not sure what error you're referring to which led you to that code - we rarely see issues there.

I'd recommend you investigate [these suggestions](https://bosh.io/docs/tips.html#unreachable-agent). If you're still experiencing issues, please include the original error messages long with more information about your environment such as director, cpi, and stemcell version information.

**Comment by zhoutiekui** [comment]
@dpb587-pivotal   thank you so much.

We had encountered the error because of our iaas problem leading the "check_instance_ips(remote_ip, instance_id) if remote_ip" code failure. and then the error response is also "timed out pinging....".

Another question, I want to know how to confirm the agent status is normal and  the agent service is running ? and what conditions are needed to make sure the agent service can be started ?

**Comment by dpb587-pivotal** [comment]
Not sure what you mean by confirming if "the agent status is normal" - you could ssh onto the vm and look at the `/var/vcap/bosh/log/current` log to see the agent log for more information? Agent is typically running fine though... issues are more to do with networking and misconfiguration on the director side. Please take a look at the [suggestions](https://bosh.io/docs/tips.html#unreachable-agent) for how to investigate the issues in more detail.
