### ISSUE TITLE
Cannot upload release with no jobs

### ISSUE THREAD

**Issue by lnhrdt** [cloudfoundry/bosh#1706]
Not sure where the issues in cf-tm-bot/bosh went, but here's a web cache of an issue that was on there that I seem to be experiencing now:

http://webcache.googleusercontent.com/search?q=cache:https://github.com/cf-tm-bot/bosh/issues/375&num=1&strip=0&vwsrc=0

I cannot upload a release with no jobs. It looks like it was fixed in c453986 / #133467507 but I'm still experiencing the issue, using `version 2.0.24-e84c20c-2017-06-01T16:25:13Z`.

Any tips?

**Comment by dpb587-pivotal** [comment]
Can you check which version of director you're running? In this case, the fix was on director, not the CLI, and it should be in [v261+](https://github.com/cloudfoundry/bosh/releases/v261).

**Comment by lnhrdt** [comment]
@dpb587-pivotal Thanks Danny! You're right.

```
Name      Bosh Lite Director
UUID      63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79
Version   260.0.0 (00000000)
CPI       warden_cpi
Features  compiled_package_cache: enabled
          dns: disabled
          snapshots: disabled
User      admin
```

Maybe BOSH Lite could get an update. We're using the latest master.

**Comment by dpb587-pivotal** [comment]
Good thought. We're in the process of transitioning people away from [cloudfoundry/bosh-lite](https://github.com/cloudfoundry/bosh-lite) to [cloudfoundry/bosh-deployment](https://github.com/cloudfoundry/bosh-deployment/blob/master/docs/bosh-lite-on-vbox.md) because bosh-deployment uses the same deployment strategy that you'd use in production and helps maintain better parity. That repo is kept up to date with recent versions. I'd recommend you try that out, next time you get a chance (and definitely interested in feedback, if you have it).
