### ISSUE TITLE
bosh stop does too much

### ISSUE THREAD

**Issue by poy** [cloudfoundry/bosh#1723]
We run into situations when we want to stop an instance group and try to use `bosh stop` to do so. However, instead of simply reaching out to those VMs and stopping them, it seems to try to repair unhealthy VMs and do other deploy steps (e.g., resolve bosh links).

This is normally fine, however when a deployment is unhealthy and different instance groups are "attacking" each other in some fashion, it becomes hard to repair it.

**Comment by cppforlife** [comment]
@apoydence we have upcoming track of work that will make deployment commands (including deploy) as granular as they can be. that would address the behaviour you are describing.

**Comment by apoydence** [comment]
Good deal. We'll watch for that. Is there a epic in tracker?

**Comment by h4xnoodle** [comment]
We have since added a new feature where you can tell bosh to leave other todo's alone when issuing `bosh stop` with `bosh stop --no-converge`. The other actions bosh was performing were 'converging' the other instances to their intended healthy state. Please let us know if this does not solve your issue.
