### ISSUE TITLE
As an operator making a deployment, I would like to know that I will exceed quotas before starting the deployment

### ISSUE THREAD

**Issue by jchesterpivotal** [cloudfoundry/bosh#1727]
When deploying to an IaaS, BOSH will ask for resources as it proceeds through the VMs, networks and so on.

Typically IaaSes will define quotas for resources like total RAM, total CPUs, total disk, total IPs and so forth. Some IaaSes make it possible to interrogate these quotas in advance (eg, GCP provides it [as part of the `project` type](https://cloud.google.com/compute/docs/reference/latest/projects)).

It is not uncommon to discover that you are lacking in one quota item (and typically only one quota item per attempted deployment) a fair way through a lengthy deployment.

At the same time, BOSH has all the information necessary to calculate what the eventual total requirements for a deployment will be. It knows about VM sizes -- CPU, RAM, Disk -- and it knows about networking configuration.

In cases where a deployment will fail due to exceeding quota, it would be useful to be warned before the deployment that this is likely.

In all cases, it would be useful to be able to see a table of deployment requirements, with expected totals and highlighting of quotas that would be exceeded, so that I can ask for quota increases as necessary.

Somewhat related: #738

**Comment by jfmyers9** [comment]
While I think this would be a nice feature, this isn't something that is a priority in our future roadmap. I'm going to close this issue as a result. If you have further questions, feel free to reopen this issue.

**Comment by dpb587-pivotal** [comment]
For anyone interested in thinking about this further, feel free to brainstorm and discuss suggestions. It's not a trivial issue; you'll want to consider things like...

 * parallel other processes and tasks may be adding/removing/changing resource usage on their own. It becomes very difficult to synchronize that.
 * API throttling itself is also related, but very difficult to synchronize as well; it's probably best left to CPIs to retry
 * multi-CPI also complicates this a bit as well since difference CPIs from `cpi-config` may have different limits, so it's no longer a global state; and while there may be multiple CPIs in `cpi-config`... they may actually be using the same account/limits
