### ISSUE TITLE
Issue while adding custom blobstore client. bosh1 does not reognize the custom blobstore

### ISSUE THREAD

**Issue by parthasarathi204** [cloudfoundry/bosh#1767]
Issue:   https://github.com/cloudfoundry/cf-release/issues/1224 while uploading the release using bosh2 even with out custom blobstore. bosh1 commands refuse to work with custom blobstore 
I have added the new 'foo' cli in bosh (https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/blobstore_client/client.rb) .

diff --git a/src/bosh-director/lib/bosh/blobstore_client/client.rb b/src/bosh-director/lib/bosh/blobstore_client/client.rb
index 4b26411..45c18da 100644
--- a/src/bosh-director/lib/bosh/blobstore_client/client.rb
+++ b/src/bosh-director/lib/bosh/blobstore_client/client.rb
@@ -1,13 +1,13 @@
module Bosh
module Blobstore
class Client
`- PROVIDER_NAMES = %w[local s3cli gcscli davcli]`
`+ PROVIDER_NAMES = %w[local foocli s3cli gcscli davcli]`
I have implemented 4 methods #create_file, #delete_object(id) , #object_exists?(id), #get_file(id, file) as mentioned in base.rb
as per http://www.rubydoc.info/gems/blobstore_client/1.3033.0/Bosh/Blobstore/SimpleBlobstoreClient

diff --git a/src/bosh-director/lib/bosh/director.rb b/src/bosh-director/lib/bosh/director.rb
index 973fec9..642c3fd 100644
--- a/src/bosh-director/lib/bosh/director.rb
+++ b/src/bosh-director/lib/bosh/director.rb
+Bosh::Blobstore.autoload(:FoocliBlobstoreClient, 'bosh/blobstore_client/foocli_blobstore_client')

s3cli and gcscli are based on cli commands . but I have not written any executable for this .

Hope that is fine as long as I am implementing those 4 methods.
 I have provided the credential details in config/private.yml and config/final.yml as per http://bosh.io/docs/reference/blobs.html , 
I am confused to make the changes in jobs/director/templates/director.yml.erb.erb.  
-- Any where can I see the changes how does it looks like for simpleBlobstoreClient for this erb file ?  
-- Any missing piece ?
none of the bosh1 commands refuse to work. Errors out as 
Cannot initialize blobstore: Unknown client provider 'foo', available providers are: ["dav", "simple", "s3", "local", "s3cli"]
bosh2 create-release for cf works but upload-release fails  . Erros out as
15:25:17 | Error: Missing template file 'newrelic.yml.erb' for job 'cloud_controller_clock'
So bosh1 does not recognize custom blobstore client . bosh2 does not upload release , whcih does not have to with the custom blobstore client . Even with out custom blobstore also bosh2 upload-release does not work. 
-- How can I resolve this ?

**Comment by dpb587-pivotal** [comment]
We typically don't recommend implementing custom blobstores for either the CLI or for director. We provide several common providers with the expectation that they'll cover a provider that everyone can find access to. Custom CLI patches also make it very difficult for others to use the releases, and custom director patches make it difficult for maintenance. Additionally, blobstore providers should now be implemented in golang for portability and reusability.

If you need further information, you may find the following PRs useful where gcscli support was added to [director](https://github.com/cloudfoundry/bosh/pull/1732) and [cli](https://github.com/cloudfoundry/bosh-cli/pull/238).

If you're intending on submitting these changes upstream, I'd be interested to hear more about the blobstore provider since we may not be able to support every provider which is out there.
