### ISSUE TITLE
Support TLS database connections

### ISSUE THREAD

**Issue by x6j8x** [cloudfoundry/bosh#1771]
As a platform operator
I want to be able to configure secure (TLS) database connections for the director & registry
In order to be compliant to corporate security requirements.  

Currently the director & registry jobs do not expose properties that would allow to configure secure database connectivity. 

Sequel does support TLS secured connectivity for instance through the `mysql2` database driver (https://github.com/brianmario/mysql2#ssl-options). 

Please extend the directory & registry job spec to allow secure connectivity to (external) backend databases.

**Comment by peterellisjones** [comment]
postgres should support this too (https://www.postgresql.org/docs/9.6/static/libpq-connect.html) using the options `sslcert`, `sslkey`, and `sslrootcert` (for mysql this last one is `sslca`). Unfortunately although the director spec allows passing in arbitrary [`connection_options`](http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=263.4.0#p=director.db.connection_options) to Sequel, the ssl keys all need to be paths to files rather than the contents of files. It would be nice to have a translation step that detected sslcert/sslkey/sslrootcert/sslca in the `connection_options` hash, wrote the values to a file, and replaced the values with their filepaths

**Comment by jfmyers9** [comment]
Hi all,

As of the latest BOSH director releases, we should be supporting TLS connections on both postgres and mysql for the director and the registry. I'm going to close this issue. Feel free to reopen it if you have any further questions.

Best,

@jfmyers9, CF BOSH
