### ISSUE TITLE
post-start didn't run on new deployment

### ISSUE THREAD

**Issue by gerhard** [cloudfoundry/bosh#1776]
I was expecting `post-start` for a job to always run, but we've recently discovered that this is not the case. This was a fresh deploy, so no VM reboot.

Is this expected?

```
Name      bosh-director-20170606
UUID      6767783b-4ca4-4e33-90e5-cbf8c6a7bfd0
Version   262.0.0 (00000000)
CPI       google_cpi
Features  compiled_package_cache: disabled
          config_server: disabled
          dns: disabled
          snapshots: disabled
User      admin
```

**Comment by cppforlife** [comment]
@gerhard what do you mean by "always" in this case? hooks will run if changes are being made, ie property is updated, etc. anytime director issues monit start.

**Comment by cppforlife** [comment]
they do not run when monit decides to restart process on its own (without director's concern).

**Comment by gerhard** [comment]
When the deployment is created, I would expect `post-start` to run. We deployed something for the first time and `post-start` didn't run. We no longer have the deployment to get the instance logs, but I am wondering whether you've seen this before.

Part of the same deployment, we have observed `pre-start` failing - could this prevent `post-start` from running?

**Comment by jfmyers9** [comment]
As mentioned, `post-start` should run on every deploy in which BOSH updates an instance. This includes initial deploys. If a lifecycle step that runs before `post-start` fails (i.e. `pre-start`, `monit start`, etc), then the deploy will exit at that point and `post-start` will not run.

I'm going to close this due to inactivity. Please feel free to reopen if you have further questions.
