### ISSUE TITLE
Certificate issue when deploying bosh on vSphere

### ISSUE THREAD

**Issue by csaunders-pivotal** [cloudfoundry/bosh#1813]
Hello,
I am running into this when deploying bosh on vsphere using the following command

bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/vsphere/cpi.yml \
    -v director_name=bosh-1 \
    -v internal_cidr=10.193.54.0/24\
    -v internal_gw=10.193.54.1 \
    -v internal_ip=10.193.54.200 \
    -v network_name="VM Network" \
    -v vcenter_dc=Datacenter \
    -v vcenter_ds=LUN01 \
    -v vcenter_ip=10.193.54.11 \
    -v vcenter_user=administrator@vsphere.local \
    -v vcenter_password=XXXX\
    -v vcenter_templates=bosh-1-templates \
    -v vcenter_vms=bosh-1-vms \
    -v vcenter_disks=bosh-1-disks \
    -v vcenter_cluster=Cluster

error below

Started deploying
  Waiting for the agent on VM 'vm-a3cb6f0c-536c-406f-903a-7473a15bff03'... Failed (00:00:00)
  Deleting VM 'vm-a3cb6f0c-536c-406f-903a-7473a15bff03'... Finished (00:00:06)
  Creating VM for instance 'bosh/0' from stemcell 'sc-f9a1fdc8-ef1f-4665-b0a9-74aa21cd1ae6'... Finished (00:00:16)
  Waiting for the agent on VM 'vm-a736e165-b92a-4c82-bc5f-2d4cf9f4c127' to be ready... Failed (00:00:22)
Failed deploying (00:00:48)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@10.193.54.200:6868/agent: x509: certificate is valid for 10.193.54.1, not 10.193.54.200

Exit code 1

**Comment by dpb587-pivotal** [comment]
This sounds like you might initially have used the ip 10.193.54.1 and then switched to 10.193.54.200. Since the CLI will currently only generate variables if they're not already present (and not when variable options/settings change), it didn't regenerate with the new IP.

The easiest way to fix (if this is a test/scratch environment) it is probably to delete your `creds.yml` file and let it regenerate everything from scratch. Alternatively, you can selectively delete the `mbus_bootstrap_ssl` and `director_ssl` key/values that you find in `creds.yml` which would cause them to be regenerated when you next run `create-env`.

**Comment by csaunders-pivotal** [comment]
ahh thanks, that was it!
