### ISSUE TITLE
Colocated errands not appearing

### ISSUE THREAD

**Issue by jacknewberry** [cloudfoundry/bosh#1835]
We've seen some inconsistent behavior with how bosh decides if a job is an errand. There seems to be variation between instance-group and colocated errands.

The difference seems to arise from the job spec file.

With `templates: [run: bin/run]` both errand types are identified by `bosh errands`.
With `templates: [run: /bin/run]` only the instance-group errand is identified. The colocated errand does not appear in `bosh errands`.

We can recreate this behaviour using the example Zookeeper release with two errands `status` and `smoke-tests`.

BOSH version is 264.

We have also found a similar issue with colocated errands not being identified even when templating into `bin/run`. Changing the errand template file name (errand.sh.erb to run) seems to resolve it, but we were not able to recreate it in Zookeeper.

**Comment by jacknewberry** [comment]
We have identified the issue as being caused by this method:
https://github.com/cloudfoundry/bosh/blob/1a6d637ddc8f15107407e581884f75224ed15a61/src/bosh-director/lib/bosh/director/models/template.rb#L70-L75
``` ruby
def runs_as_errand?
      return false if templates == nil

      templates.values.include?('bin/run') ||
        templates.values.include?('bin/run.ps1')
    end
```

Which is eventually called from here: 
https://github.com/cloudfoundry/bosh/blob/391e66347870f782964aac7cc5a7e63576b638c3/src/bosh-director/lib/bosh/director/api/controllers/deployments_controller.rb#L458

Instance-group errands have a different discovery path so they are not affected.

Both job and instance-group errands seem to be templated the same whether they specify the template path as `bin/run` or `/bin/run`.

**Comment by dpb587-pivotal** [comment]
Hi - director doesn't currently error on it, but all template installation paths should be relative and not prefixed by `/` (since it's not absolute). I guess errands is the first feature to implicitly force that. It looks like you have updated your release to make them relative, which is the correct thing to do.

We may be able to build tooling to help surface this sort of potential issue (e.g. cppforlife/bosh-lint#16), but not sure if director will start validating anytime soon since there may be many other releases and older release versions still rely on it.
