### ISSUE TITLE
Deploy of 264.3.0 fails with job error.

### ISSUE THREAD

**Issue by jhedman2** [cloudfoundry/bosh#1843]
Validation during the deploy phase was failing no matter what with version 264.3.0.  Specifically validation failed with the error: 
bosh deploy failed jobs[0].templates[1] must refer to a job in bosh but there is no job named 'postgres'

After digging around a lot, i was able to get the validation to succeed if I forced the postgres template to be called 'postgres-9.4' instead of just 'postgres'.  Hope this might help others.

**Comment by dpb587-pivotal** [comment]
Hi - sounds like you might be upgrading from versions prior to v262, which is when we removed the `postgres` job in favor of `postgres-9.4`. The [v262 release notes](https://github.com/cloudfoundry/bosh/releases/tag/v262) mention a few other changes, and I'd recommend checking the release notes of the other releases as well since there have been a few other changes in recent versions, too.

**Comment by jhedman2** [comment]
Unfortunately no, this was a brand new build i started today...  i'll look at the release notes though, thank you.

**Comment by dpb587-pivotal** [comment]
If there are particular docs you are following, please feel free to mention them and we can make sure they are updated if a sample 264.3.0 configuration is still referring to `postgres`.

**Comment by jhedman2** [comment]
Absolutely, apologize.  Here's the document i was following: https://bosh.io/docs/init-vsphere-v1.html

**Comment by cppforlife** [comment]
any reason why not use default vsphere doc:
https://bosh.io/docs/init-vsphere.html ?
