### ISSUE TITLE
bbr backup does not support pg 9.6

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh#1886]
as we can see in line https://github.com/cloudfoundry/bosh/blob/master/jobs/director/templates/bbr_backup#L12

the bbr backup script does not support 9.6.
now i know bosh it self is not on 9.6 yet.
but in bucc we are colocating `bosh, uaa, concourse, credhub`
and concourse needed 9.6

so in our case bosh is on postgres 9.6.

so i was wondering if you accept a pull request where it checks for 9.6 version just like in
https://github.com/pivotal-cf/credhub-release/blob/master/jobs/credhub/templates/backup.erb#L28
credhub depends on backup-restore-sdk
but i think we can just check if this package exists before checking that if statement.

**Comment by tjvman** [comment]
@ramonskie Is there a reason why you want Concourse and Director's postgres versions to agree? It's fine to have Concourse running against 9.6 and Director running against 9.4, just need to make sure that the manifest is configured correctly and that the databases run on different ports.

**Comment by rkoster** [comment]
It seemed like a good idea since more and more releases are switching to using: [postgres-release](https://github.com/cloudfoundry/postgres-release), instead of maintaining their own postgres ([cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-postgres.yml#L6), [concourse](https://github.com/concourse/concourse-deployment/blob/master/cluster/concourse.yml#L16)).
Also we have been using the same postgres for concourse and the director for almost a year now. And I don't see an easy way to migrate existing users to 2 different postgres processes without manual steps (as in just 1 `bosh create-env`).

**Comment by ramonskie** [comment]
in the meantime i solved it with https://github.com/ramonskie/fakepackage-boshrelease

**Comment by ramonskie** [comment]
EDIT:
above won't work because of hard coded library path in `backup.erb` & `restore.erb`

so will you accept a PR?
so that bosh will also accept the use of pg 9.6 in backup/restore scripts?

**Comment by dpb587-pivotal** [comment]
We're [currently working](https://www.pivotaltracker.com/n/projects/956238/search?q=label%3A%22bbr2%22) on improving database backup behavior with bbr, and I don't think this will be an issue once that is complete and released. Let's wait on a pull request until that change is finished so you can try it out and verify it fixes the issue.

**Comment by xtreme-andrew-su** [comment]
@ramonskie with the completion of https://www.pivotaltracker.com/story/show/157571931 and https://www.pivotaltracker.com/story/show/157569428 perhaps your specific usecase is handled? I'm closing this issue for now, please feel free to reopen if the issue still persists.
