### ISSUE TITLE
Integration of bosh VMS with LDAP authentication 

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry/bosh#1893]
Hi Folks,

Is there a document which you can point me to integrate bosh created VMS with ldap authentication ?If we need to customize stem cell could you point me to that document location ?

**Comment by dpb587-pivotal** [comment]
I am unclear on what sort of integration you are looking for. If you're looking for integrating BOSH with LDAP authentication, you can do this via [cloudfoundry/uaa-release](https://github.com/cloudfoundry/uaa-release) and their LDAP support paired with BOSH's [UAA integration](http://bosh.io/docs/director-users-uaa.html). If you're looking for individual VMs authenticating and registering to an LDAP server, that's not something which is inherently supported, but you could build software that can be deployed onto VMs to do that.

**Comment by nsharmacovs** [comment]
Thanks, i was looking for part second of your answer .

**Comment by cppforlife** [comment]
@nsharmacovs are you referring to ssh integration with ldap?

**Comment by ramonskie** [comment]
@cppforlife i'm interested in ssh integration with ldap

**Comment by cppforlife** [comment]
@nsharmacovs @ramonskie i've never done this myself, but i suspect it's an sshd configuration that could be added via a new job (that's installed as an addon everywhere). job's pre start script could update sshd config and configure pam to use ldap auth (not sure if some new module needs to be installed for that). 

may be @cunnie knows more about set up of plain ldap ssh integration?

**Comment by cunnie** [comment]
@nsharmacovs @ramonskie Yeah, setting up LDAP integration shouldn't too hard (I assume you've already set up your LDAP server). Essentially you'll need to create a BOSH Release which does the configuration as an LDAP client. Also, remember to include any userids created in the `bosh_sshers` group (and probably the `bosh_sudoers` group if you want them to have `sudo` access`.

It's been a decade since I set up an LDAP client, but I've include some notes from ten years ago about the process. They're probably wrong, the landscape has changed, but they might point you in the right direction.

You'd probably want to go through the steps by hand on a BOSH-deployed VM (first get on the VM by running `bosh ssh` and begin your configuration). Once you do it manually you can begin writing a release. Good luck.

```
Tue Apr 22 16:36:19 PDT 2008

cd /etc
mrcs
echo iv | ci -l /etc/ldap.conf
sudo mv -i /etc/ldap.conf /tmp/
sudo ln -s /etc/openldap/ldap.conf /etc/
cd /etc/openldap
mrcs
echo iv | ci -l ldap.conf
sudo vim ldap.conf
    base dc=ardatech,dc=com
    uri ldaps://ldap.ardatech.com/
    tls_cacert /etc/openldap/cacerts/ldap.ardatech.com
    pam_password md5
openssl s_client -connect vazir:636
# copy cert into /tmp/ssl.cert
openssl s_client -connect vazir:636 -CAfile /tmp/ssl.cert
sudo cp /tmp/ssl.cert /etc/openldap/cacerts/ldap.ardatech.com
sudo rsync -avH vazir:/usr/local/etc/openldap/cacert.pem /etc/openldap/cacerts/
sudo rsync -avH vazir:/usr/local/etc/openldap/ldap.ardatech.com.pem /etc/openldap/cacerts/

Thu Apr 24 16:52:07 PDT 2008

I have been having problems changing my ldap password, but I
configured the ldap client using the gui and that fixed it.

sudo system-config-authentication

This is ldap.conf:

    host ldap.ardatech.com
    ssl start_tls
    TLS_CACERTDIR /etc/openldap/cacerts
    pam_password md5
    HOST ldap.ardatech.com
    BASE dc=ardatech,dc=com

And it modified this file:  /etc/pam.d/system-auth

cd /etc/pam.d
echo iv | ci -l system-auth
# you have to remove "use_authtok" from the ldap line
sudo vim system-auth
    #password    requisite     /lib/security/$ISA/pam_cracklib.so retry=3
    password    sufficient    /lib/security/$ISA/pam_unix.so nullok md5 shadow
    password    sufficient    /lib/security/$ISA/pam_ldap.so
```

**Comment by dpb587-pivotal** [comment]
Closing - thanks @cunnie for the #protips!
