### ISSUE TITLE
Error 100: Job 'postgres' not found in Template table

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry/bosh#1909]
Hi ,
we are upgrading bosh  from v261.4 to v264.8.0  , its giving an error 

  Started preparing deployment > Preparing deployment. Failed: Job 'postgres' not found in Template table (00:00:00)

Error 100: Job 'postgres' not found in Template table

Can you please suggest something on this.

**Comment by jhiemer** [comment]
@lordcf show the deployment manifest of your bosh director.

**Comment by dpb587-pivotal** [comment]
Hi - the `postgres` job was removed in [v262](https://github.com/cloudfoundry/bosh/releases/tag/v262), and you will probably want to switch to `postgres-9.4`. I would recommend reviewing the release notes, as there are other breaking changes since the version you are upgrading from.

You may also want to check out [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) as an alternative to managing your own manifest.

**Comment by cppforlife** [comment]
> You may also want to check out bosh-deployment as an alternative to
managing your own manifest.

strongly recommended

**Comment by lordcf** [comment]
HI,
we tried using job postgres-9.4, now facing the error as shown below.

Error 80011: Package name collision detected in instance group 'bosh': job 'bosh/postgres-9.4' depends on package 'bosh/postgres-9.4', job 'shield/shield-agent' depends on 'shield/postgres-9.4'. BOSH cannot currently collocate two packages with identical names from separate releases.

**Comment by dpb587-pivotal** [comment]
Since packages are installed at predictable paths (e.g. `/var/vcap/packages/postgres-9.4`) you are not able to use two packages with the same name from different releases. Depending on your environment and needs, you should probably decide to use only one of the packages to provide the database service.
