### ISSUE TITLE
Upload Stem Cell Error - Keystone connection timed out

### ISSUE THREAD

**Issue by avirkar** [cloudfoundry/bosh#1928]
I am getting the following error while uploading the stem cell to bosh vm on openstack.  I am able to upload releases but failing only while uploading stem cells. I am using bosh cli v2. 

> bosh -e sdp-bosh-env upload-stemcell https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3541.12 --fix
Using environment '10.82.73.8' as client 'admin'

Task 13

Task 13 | 05:02:40 | Update stemcell: Downloading remote stemcell (00:00:51)
Task 13 | 05:03:31 | Update stemcell: Extracting stemcell archive (00:00:03)
Task 13 | 05:03:34 | Update stemcell: Verifying stemcell manifest (00:00:00)
Task 13 | 05:03:35 | Update stemcell: Checking if this stemcell already exists (00:00:00)
Task 13 | 05:03:35 | Update stemcell: Uploading stemcell bosh-openstack-kvm-ubuntu-trusty-go_agent/3541.12 to the cloud (00:10:41)
                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Unable to connect to the OpenStack Keystone API http://10.81.102.5:5000/v2.0/tokens
Connection timed out - connect(2) for 10.81.102.5:5000 (Errno::ETIMEDOUT)' in 'create_stemcell' CPI method
Task 13 | 05:14:16 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Unable to connect to the OpenStack Keystone API http://10.81.102.5:5000/v2.0/tokens
Connection timed out - connect(2) for 10.81.102.5:5000 (Errno::ETIMEDOUT)' in 'create_stemcell' CPI method

Task 13 Started  Sat Apr  7 05:02:40 UTC 2018
Task 13 Finished Sat Apr  7 05:14:16 UTC 2018
Task 13 Duration 00:11:36
Task 13 error

Uploading remote stemcell 'https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent?v=3541.12':
  Expected task '13' to succeed but state is 'error'

Exit code 1

**Comment by friegger** [comment]
@avirkar 
BOSH downloads the stemcell and afterwards uploads it to your OpenStack's image service Glance via the OpenStack CPI. Before connecting to the individual OpenStack service clients always contact the identity service Keystone in order to authenticate and discover available services. This call times out, which indicates, that the BOSH VM cannot reach the auth url configured here: https://github.com/cloudfoundry/bosh-deployment/blob/master/openstack/cpi.yml#L68

In contrast `upload-release` does not communicate with the OpenStack API and hence does not yield the same error.

Please ensure that the BOSH VM can reach to the OpenStack API. You can find documentation which might help you setting up the infrastructure properly here:
https://bosh.io/docs/init-openstack.html

Closing this. Please reopen, in case the issue persists.
