### ISSUE TITLE
Need basic idea on bosh architecture 

### ISSUE THREAD

**Issue by wilfredwilly** [cloudfoundry/bosh#1933]
Hi

Deployed CF on AWS using BBL and cf-deployment using the following document

https://docs.cloudfoundry.org/deploying/common/aws.html

Need to understand why  components/instance (bosh/0,  jumbox/0,  bbl-env-saimaa-2018-04-02t10-13z-nat) have been created in aws infrastructure when executing the below command

$ bbl plan \
    --iaas aws \
    --aws-access-key-id YOUR-ACCESS-KEY-ID \
    --aws-secret-access-key YOUR-SECRET-ACCESS-KEY \
    --aws-region YOUR-AWS-REGION \
    --lb-type cf \
    --lb-cert YOUR-CERT.crt \
    --lb-key YOUR-KEY.key \
    --lb-domain YOUR-SYSTEM-DOMAIN

$ bbl up

2)How to Login into bosh/0 and  bbl-env-saimaa-2018-04-02t10-13z-nat instance. 

3) Need to know why three load balance has been created and the use.

bbl-env-sa-db7a86b-cf-router-lb
bbl-env-sa-db7a86b-cf-ssh-lb
bbl-env-sa-db7a86b-cf-tcp-lb

**Comment by cppforlife** [comment]
> Need to understand why components/instance (bosh/0, jumbox/0, bbl-env-saimaa-2018-04-02t10-13z-nat) have been created in aws infrastructure when executing the below command

bbl up is what creates these components. it configures env to work in a secure by default manner. is there a particular question about this setup you have? @evanfarrar @genevieve from the bbl team may have more info.

**Comment by genevieve** [comment]
Hey @wilfredwilly. We can also answer you over on github.com/cloudfoundry/bosh-bootloader.

1. For AWS, there are 3 instances created with their own purpose. 

- `bosh/0` is your BOSH director
- `jumpbox/0` is your bastion/jumpbox that lies in front of your BOSH director that you have to proxy commands through and allows us to limit the ports and incoming traffic on the director instead of exposing it to the whole internet
- `bbl-env-saimaa-2018-04-02t10-13z-nat` is the NAT box required on AWS

2. You can reach `bosh/0` with this document: https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/howto-ssh.md#to-the-bosh-director

3. There are three load balancers each for different kinds of traffic.

**Comment by cwlbraa** [comment]
The load balancers are used by the cloud foundry deployment that you'll be wanting to deploy onto that bosh director. 

* `bbl-env-sa-db7a86b-cf-router-lb` is going to load balance http[s] requests through the gorouter to your cloud foundry application containers pushed by `cf push $APP`.
* `bbl-env-sa-db7a86b-cf-ssh-lb` is going to load balance ssh tunnels through the diego brain ssh proxy to your cloud foundry application containers when you run `cf ssh $APP`.
* `bbl-env-sa-db7a86b-cf-tcp-lb` is going to load balance tcp requests through the tcp router to your cloud foundry application containers pushed by `cf push $APP`.

**Comment by wilfredwilly** [comment]
Can i delete the 3 loadbalancer (bbl-env-sa-db7a86b-cf-router-lb,bbl-env-sa-db7a86b-cf-ssh-lb, bbl-env-sa-db7a86b-cf-tcp-lb)and recreate when it is need?

**Comment by genevieve** [comment]
You can run `bbl plan` without the `--lb-type` flags and this will write out terraform files without the load balancer resources. When you run `bbl up`, it will execute `terraform apply` and the load balancers will be destroyed.

**Comment by wilfredwilly** [comment]
Thanks a log @genevieve 
How to change the stemcells(centos)  and instance type for bosh/0, jumbox/0, bbl-env-saimaa

**Comment by dpb587-pivotal** [comment]
If you're interested in customizing the defaults that bbl will provide, I'd recommend referring to bbl's [docs/customization.md](https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/customization.md) for more information. Note that some releases/configurations may not be supported on CentOS stemcells, so you should probably only switch if there's a specific reason or need.

Since this has become more focused on bbl usage, I'm going to close this issue. Feel free to join [cloudfoundry.slack.com#bbl-users](https://slack.cloudfoundry.org/) for more help on bbl, or create a new issue here or in [bosh-bootloader](https://github.com/cloudfoundry/bosh-bootloader) for more information on one of the components.
