### ISSUE TITLE
Methods to access different components of Cloud Foundry Container Runtime (CFCR)

### ISSUE THREAD

**Issue by mukeshrajmca** [cloudfoundry/bosh#1934]
What are the methods to access different components of CFCR. I could login to credhub and got kubernetes certificate and credentials , then I tried accessing kubernetes dashboard component with CURL command with –cacert option but did not work out.

**Comment by dpb587-pivotal** [comment]
I'd recommend referring to the [Access Kubernetes](https://docs-cfcr.cfapps.io/installing/deploying-cfcr/#step-4-access-kubernetes) section of the [CFCR docs](https://docs-cfcr.cfapps.io/).

Since this is specific to CFCR rather than general BOSH usage and issues I'm going to close this issue. If you still need help I'd recommend joining [cloudfoundry.slack.com#cfcr](https://slack.cloudfoundry.org/) for more help and suggestions.
