### ISSUE TITLE
Allow compiled releases to float across any stemcell version

### ISSUE THREAD

**Issue by xoebus** [cloudfoundry/bosh#1946]
I'm working on some different tooling to build pre-built compiled releases. It would be extremely helpful if I could put a property in the release manifest that would tell the director that the compiled bits in the release were valid for any stemcell version. As the release author I would take responsibility for maintaining binary compatibility.

**Comment by cppforlife** [comment]
one option is to record stemcell compatibility in a more generic format in release.MF. 

@xoebus would you want this to "cover" multiple types of stemcells as well, eg trusty and xenial?

**Comment by xoebus** [comment]
I think that the static binaries I'm planning on building would probably work on both but I'd be fine with not being able to float across multiple stemcell types and just being able to float across stemcell versions.

Do you mean that something like this could be added to the `release.MF`?

``` yaml
stemcell: "~> 1.3"
```

Like in a Gemfile etc?

**Comment by cppforlife** [comment]
ive been thinking more about this and i think we should take an alternative approach: instead of using compiled_packages we should have some packages allow skipping compilation. this is something that @mkocher proposed a long long time ago for buildpacks, but would also fit nicely over here. we could probably add some flag in packages/x/spec yml to indicate that there is no need to compile, and director can just use it for any stemcell version.

**Comment by xoebus** [comment]
Neat.

Do you have a proposal of what the spec and release tarball would look like?

**Comment by cppforlife** [comment]
Added: https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/compileless-packages.md, though need a better name...

**Comment by mfine30** [comment]
@xoebus is this still a thing?

**Comment by xoebus** [comment]
Very much so.
