### ISSUE TITLE
Wildcard support in placement rules

### ISSUE THREAD

**Issue by antonsoroko** [cloudfoundry/bosh#1957]
Hello.

Deployment name in PCF has dynamic postfix, so it would be nice to have wildcard support to easy include/exclude deployments in any foundation.
I mean, if customer has a lot of foundations, he can use the same runtime-config for all of them.

Also it would easier for vendors of addons to provide snippets of runtime config.

Thanks.

**Comment by dpb587-pivotal** [comment]
@cppforlife true. But that is something the operator may want to take responsibility for. I don't imagine it should be used for PCF since those behaviors are more controlled, but I could see it being useful for those maintaining their own platform and operations teams who may define conventions for their environments.

**Comment by antonsoroko** [comment]
@dpb587-pivotal 
Hello.
In my case it is more about PCF. It is really boring to create unique exclude rules for every foundation (e.g. p-mysql-12345, p-mysql-98765 and so on and so forth).
Thanks.

**Comment by cppforlife** [comment]
@antonsoroko is there a better rule you can write, potentially using `teams` selection? (you can find teams via `bosh deployments` cmd)

**Comment by mfine30** [comment]
Hey @antonsoroko in regards to the wildcard solution, we haven't heard a ton of need for it more broadly. Before we make such a impactful feature, I'd want to hear more from folks about a need for it. As a result, I'm going to close this for now.
