### ISSUE TITLE
Not authorized: '/deployments'

### ISSUE THREAD

**Issue by surazzarus** [cloudfoundry/bosh#1971]
After login as bosh.admin

Successfully authenticated with UAA
Succeeded

I tried to get the deployments using curl, according to
https://bosh.io/docs/director-api-v1/

curl -v -s -k https://bosh-director-ip:25555/deployments | jq .

But I get not authorized

**Comment by dpb587-pivotal** [comment]
It looks like you are attempting to use both the BOSH CLI and manual curl commands. When logging in via `bosh`, that authentication information will only be used by BOSH (it's not available to `curl` since additional headers are required to authenticate). You may want to use the `--json` option if you are looking to use programmatic output. For example, would `bosh deployments --json` get you the information you're looking for?

**Comment by surazzarus** [comment]
@dpb587-pivotal thank you for the reply. I would like to get the deployments of bosh using the Director REST API. `bosh deployments` give me the deployments after i am logged in. But how about using curl.. What are the additional headers required?
I tried:
curl -s -k https://admin:password@10.0.2.252:25555/deployments

I get same not authorized

**Comment by dpb587-pivotal** [comment]
The API is documented at [here](http://bosh.io/docs/director-api-v1/), although I don't think it specifically mentions authorization. For UAA, you'll need to pass the token received as part of the authentication process flow using the authentication type of `bearer`. You'll need to read up a bit more about UAA/JWT token management if you want to get into that.

Can you describe your use case a bit more? We generally avoid recommending the API in favor of using the bosh-cli as a library or `bosh --json ...` since it abstracts most of the internal details which may change between BOSH versions.

**Comment by surazzarus** [comment]
I did check the [uaa/UAA/Token](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-Tokens.md) and still couldn't figure it out about getting the access token. I am still trying though.

I am making a service that calls the Director HTTP API to get the list of my deployments, so that I don't have to login into the bosh-cli to get the details about my deployments.

**Comment by dpb587-pivotal** [comment]
Hmm, if you are looking for automating authentication, it sounds more like you should be looking into UAA client keys and secrets - these are intended for systematic access. These values can be passed through environment variables (`BOSH_CLIENT`, `BOSH_CLIENT_SECRET`) and avoid the need for you to run `bosh login`. I'd recommend giving that a try.

**Comment by mfine30** [comment]
Looking at those thumbs up emoji's looks like Danny's answer was sufficient to solve your problem. I'm going to go ahead and close this issue, but feel free to re-open it if it's still a problem
