### ISSUE TITLE
Missing packages in Ubuntu Xenial

### ISSUE THREAD

**Issue by Onke** [cloudfoundry/bosh#1986]
Hi there,

we were using the Ubuntu Trusty image and now want to use the Ubuntu Xenial image. Within our bosh deployment, we use the [capi-release](https://github.com/cloudfoundry/capi-release) to mount a NFS share. But the Ubuntu Xenial image does not include the nfs-common package, so the mount fails. The Ubuntu Trusty image does. Is there a reason why it's missing in the Trusty image? Or is it possible to get the package on some other ways into the stemcell?

BR
Onke

**Comment by cppforlife** [comment]
@Onke we've decided to remove these packages from the stemcell as they are not needed by 99% of releases (we've been planning to do so for some time now but just did not want to do it on trusty stemcell). more targeted solution here is for capi-release (or some additional release) to include nfs bits instead of relying on the stemcell to have them.

capi team is aware of this change in xenial stemcell and will be working to address it at some point. i would recommend reaching out to them via slack or filing issue against their repo.
