### ISSUE TITLE
delete deployment should offer details regarding timeout

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [cloudfoundry/bosh#2000]
Running `bosh2 -n -d $DEPLOYMENT delete-deployment` timeout out with a terse message:
```
Task 38399. Timeout

Deleting deployment 'ipsec-certificate_expiration_2-ubuntu-trusty':
  Expected task '38399' to succeed but state is 'timeout'

Exit code 1
```

It would be nice to know what part of the operation timed out (job drain? vm deletion?) so that the root cause can be determined or the relevant timeout increased.

director:
bosh-google-kvm-ubuntu-trusty-go_agent/3586.24
bosh/266.4.0             
bosh-google-cpi/27.0.1
bpm/0.6.0
os-conf/18

cli: 3.0.1-712bfd7-2018-03-13T23:26:42Z

**Comment by dpb587-pivotal** [comment]
Regarding the first error (`state is 'timeout'`)... this happens when the task is started by director, but at some point the worker misses heartbeats and is assumed died/crashed. This typically happens if your director is under very high load, or some other bug has caused the crash. If you want to investigate, you will probably find more information in the logs of `/var/vcap/sys/log/director/*_worker.*.log` files. As you noted, this is unfortunately a fairly low-level error and, surprisingly, happened very early in the process before the deletion fully started, causing minimal output.

The second error (`timed out sending 'run_script'`)... this happens when the worker handling the task tries to communicate with the VM to tell it a command. Internally, the worker never received acknowledgement from the VM. This typically happens if the deployment VM is under high load and not able to respond in a timely manner.

Does that information match what may be going on in your environment?

**Comment by xtreme-conor-nosal** [comment]
Yes, we needed to scale up our director - concourse pipelines were kicking off many deployments in parallel.

Could the first error message be explicit (e.g. timed out waiting for response from director or director timed out waiting for worker)?

**Comment by freddesbiens** [comment]
Closing and re-opening this issue to have a Tracker story created.
