### ISSUE TITLE
As a BOSH user, I would like to be notified about soon to expire certificates

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [cloudfoundry/bosh#2012]
It would be beneficial for the BOSH director to report back the expiry date of the certificates used in the system (director, NATS, blobstore, UAA, etc... related certificates). Maybe `bosh env` can be expanded to report that.

Also would be nice for the BOSH CLI to print a warning on each command output when it sees that the BOSH director certificate it is communicating with is about to expire in certain number of weeks.

This will be beneficial as an early warning to rotate the necessary certificates.

**Comment by mfine30** [comment]
@pivotal-jamil-shamy definitely a fan of trying to expose this to operators in some fashion. I'm not sure I agree with `bosh env` though and if there's a better spot.

Additionally, how does credhub play into this? And are we scoping this specific issue just to the certs that the BOSH "system" is using, rather than also including the various certs in the deployments?

**Comment by pivotal-jamil-shamy** [comment]
@mfine30 

> I'm not sure I agree with bosh env though and if there's a better spot.

I can see it as a dedicated BOSH CLI command (see below)

> Additionally, how does credhub play into this? And are we scoping this specific issue just to the certs that the BOSH "system" is using, rather than also including the various certs in the deployments?

Now that you have mentioned that, what about a BOSH CLI command (maybe `bosh check-certificates` or along its meaning) that does the following:

1.  `bosh check-certificates --system` will display the validity of certs used by the BOSH "system" components
2. `bosh check-certificates --deployment=<deployment-name>` will display all the certs used a certain deployment and their expiry date (including certs consumed from other deployments using cross-deployment links). We already save all the variables versions IDs that are used by a specific deployment at any point in time (although we do not save the type of variables if it is a cert or not, so there maybe some work there).

In addition to a BOSH CLI feature that will throw a warning on each command if the director cert is will expire in x number of weeks.

wdyt ?

**Comment by h4xnoodle** [comment]
I really like this idea. 

In addition to the suggestion to add `bosh check-certificates` it may also be a good idea to report any cert expiry dates after a `bosh deploy`, whether they are new or the same certs as a previous deploy. 

The reason I would want to add this after a deploy is that this command could be the only one an operator uses, then leaves the system running.

If using healthmonitor with email set up, it may also be nice to receive an email about expiring certificates.

**Comment by dpb587-pivotal** [comment]
A `check-certificates` subcommand seems too use-case specific to me as a first step. Can we can generalize this a bit more? I also think it'd be helpful to separate out the scenarios of create-env and deployment because they're significantly different.

For deployments, I see this as more dealing with generic variables. Currently I think `vars` exposes names/ids, but could we start providing additional metadata in that command? By metadata, I'd expect to minimally be things related to the "quality" of the variable, not configuration or actual values. This could also include values like the date a password was set for enforcing rotations/lifetimes.

For create-env, I think it's a bit more tricky because then we're introducing an entirely new director API for it to be self-aware of the services its running and their possible properties. For example, do we expose NATS, director, or what about CPI-specific OpenStack/vSphere certs, or external, colocated certs like databases or other APIs?

I've seen this sort of thing implemented via banner messages before, often shown during login/authentication which would make it more noticeable than `bosh env`... but could become noisy in the client-auth world where it's shown for every command. Banner messages would need to be dynamically or internally built, which might not be cheap in runtime.

Another place I've seen this implemented is through health checks or telemetry. Services can report their cert lifetimes as metrics which allow monitors to be configured and watching. In `create-env` world, this, again, is a bit more difficult since we don't currently forward director metrics to the local health monitor as a lazy way to forward off the system. More generically, this is also a bit more difficult since we don't currently expose or have published conventions around telemetry.

Just some food for thought as we continue discussing.

**Comment by gberche-orange** [comment]
> Another place I've seen this implemented is through health checks or telemetry. Services can report their cert lifetimes as metrics which allow monitors to be configured and watching.

FYI, a related community contribution enables monitoring credhub entries in external systems (prometheus in this case) and trigger alarms when they are close to expiration. See https://github.com/bosh-prometheus/prometheus-boshrelease/pull/241

Such monitoring of credhub entries would however fail to detect that a bosh deployment isn't yet using the latest version of a given credential in credhub.

/CC @psycofdj

**Comment by aeijdenberg** [comment]
We recently contributed a PR that allows for certificate rotation within a bosh deployment (not the bosh certs itself) here: https://github.com/cloudfoundry/bosh-cli/pull/490

The linked [README](https://github.com/govau/bosh-cli/blob/govau/rotation/README.md) includes a variant of our bash scripts we run as part of our CD that stops the deploy if it detects certificates (in either credhub or creds.yml) that are expiring with 30 days.

**Comment by freddesbiens** [comment]
We are addressing this though this epic: https://www.pivotaltracker.com/epic/show/4121599. Closing the issue.

**Comment by aeijdenberg** [comment]
@freddesbiens - the linked epic refers to rotations of certificates declared in bosh manifests.

The start of this issue talks about certificates managed by the director itself - this is probably quite distinct.

e.g. bosh agent certificates

**Comment by freddesbiens** [comment]
@aeijdenberg Thank you for your comment. Although the epic's description does not mention it, it contains stories focused on the director's certificates as well:

- API to check the status of the director's certificates: https://www.pivotaltracker.com/story/show/160199794
- CLI command to print the status of the director's certificates: https://www.pivotaltracker.com/story/show/158631742

**Comment by scottillogical** [comment]
Thank you for this feature - it has been very useful for us.   I wrote a simple job that collects all this data for our bosh directors and posts to slack weekly
![image](https://user-images.githubusercontent.com/130153/62889381-461d5f80-bd0f-11e9-8083-1204dfbe25cf.png)


Would adding DNS Cert expirations to this output be appropriate?

**Comment by h4xnoodle** [comment]
> Thank you for this feature - it has been very useful for us. I wrote a simple job that collects all this data for our bosh directors and posts to slack weekly
> ![image](https://user-images.githubusercontent.com/130153/62889381-461d5f80-bd0f-11e9-8083-1204dfbe25cf.png)
> 
> Would adding DNS Cert expirations to this output be appropriate? We also need to monitor bosh dns certificate expiration yearly and are probably going to manually get the data from bosh runtime-config or the secret store in the meantime

Could please open another issue/proposal for adding the DNS certs? We will be able to track the idea better this way.

A workaround at the moment would be to extract the DNS certs from `bosh int creds.yml --path /path/to/cert` and then `openssl x509 -dates -in <cert> -out`.

Thanks,
Rebecca, BOSH

**Comment by scottillogical** [comment]
Yep thats exactly what we do to workaround right now, will do thanks!
