### ISSUE TITLE
uploading a stemcell issue.

### ISSUE THREAD

**Issue by techie20122018** [cloudfoundry/bosh#2014]
Hi,

Not sure why I am getting the below exception while uploading the stemcell . I am able to upload the release.

bosh -e bosh-director-test upload-stemcell bosh-stemcell-3586.25-vsphere-esxi-ubuntu-trusty-go_agent.tgz

Error: Relative paths are not allowed in this context. The following must be be switched to use absolute paths: 'dns_recursor_ip'

Thanks

**Comment by dpb587-pivotal** [comment]
This can happen if your cloud-config is using `((dns_recursor_ip))` to pull variables from CredHub or your config server. In a deployment context, `dns_recursor_ip` becomes prefixed with a deployment-specific path; but for cloud-config, we ask that you be explicit about the variable path since it is not relative. So, instead, you probably want to refer to your cloud-config variables as `((/dns_recursor_ip))`, with the starting `/`.

**Comment by techie20122018** [comment]
The bosh director is already deployed . uploading the stemcell is creating below exception,
Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (hostname:443)' in 'create_stemcell' CPI method
Task 13 | 18:05:15 | Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (hostname:443)' in 'create_stemcell' CPI method

**Comment by dpb587-pivotal** [comment]
It sounds like the error has changed? Can we close this in favor of the [other issue](https://github.com/cloudfoundry/bosh/issues/2016) you created?

**Comment by techie20122018** [comment]
yes

**Comment by mfine30** [comment]
Closing comment above.
