### ISSUE TITLE
Speed up disk resizing by copying data before stopping jobs

### ISSUE THREAD

**Issue by giner** [cloudfoundry/bosh#2021]
Resizing a big disk is taking very long time now which is critical for single node jobs (such as blobstore).

What do you think about applying the following approach?

1. Create a new disk and attach to a VM.
2. rsync (with `--bwlimit` set to something reasonable) all files from the current disk to a new one
3. Stop all jobs
4. rsync once again without `--bwlimit` and with `--delete` option
5. Unmount both disks -> mount the new one to the right place -> detach the old one
6. Start all  jobs

This should be pretty safe as we don't have to rely on implementation of resizing on infrastructure side and at the same time downtime will not be that long as it currently is.

Issue #1569 is partially related to this one.

**Comment by voelzmo** [comment]
This might be stupid question, but looking at your description this immediately popped up in my mind: If you're not stopping the job before calling `rsync`, how are you avoiding that you're ending up with a stale copy? I understand that you're specifically targeting jobs with a huge persistent disk, so my assumption is `rsync --bwlimit <reasonable amount here>` will take a non-zero amount of time to complete. The files that have been `rsync`ed first might already be out of date when the entire operation finishes. Is there something I'm missing or are you saying this would be a risk you are willing to take?

**Comment by klakin-pivotal** [comment]
FYI, I see some evidence that suggests that GCP and AWS let you increase the size of already-mounted disks: 

https://cloud.google.com/sdk/gcloud/reference/compute/disks/resize

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/requesting-ebs-volume-modifications.html

It looks like Azure _might not_ permit live-resizing: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/expand-os-disk

And I'm fairly certain that -in vSphere- you can _increase_ the size of a disk that's attached to a running VM, and you _might_ be able to shrink it, if you've taken steps at the OS level to reduce the FS and partition size beforehand.

**Comment by voelzmo** [comment]
@klakin-pivotal resizing disks was implemented a while back as [an option in BOSH](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=271.8.0#p%3ddirector.enable_cpi_resize_disk) and for the [OpenStack CPI](https://github.com/cloudfoundry/bosh-openstack-cpi-release/releases/tag/v33) as well. It turned out we missed an important bit, though: resizing the filesystem to take advantage of the bigger disk space. AFAIK this was never properly cleaned up, though and therefore doesn't work as expected.

@friegger summed up the current state on this perfectly in https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/109#issuecomment-781343505

Some additional context: the rate limit for resizing disks on AWS is once per 6 hours, which seemed a bit weird, but might still work for your use-cases.

**Comment by klakin-pivotal** [comment]
Hah! Yeah, resizing the underlying FS is _pretty_ important. :D

If AWS reports a useful "disk resizing rate limit hit" error message _before_ you've blown a bunch of time trying to resize, then I would expect that the CPI should be able to fall back to the current slow method. However, this would be a shortcoming that would _really_ need to be documented.
