### ISSUE TITLE
A redundant stemcell record after running "bosh upload-stemcell --fix"

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#2026]
There is a redundant stemcell record  after running `bosh upload-stemcell --fix`, I think there should be only one record shown in `bosh vms`. We used bosh release `267.2`.

```
Name                                     Version    OS             CPI               CID
bosh-bluemix-xen-ubuntu-xenial-go_agent  97.3.1*    ubuntu-xenial  -                 1997987
~                                        97.3.1*    ubuntu-xenial  softlayer_ng      1997987
```

**Comment by jfmyers9** [comment]
Hey @mattcui,

This happens when you have added a CPI config after previously uploading a stemcell to a director without a CPI config.

When a director does not have a CPI config, it's default cpi is `""`. After uploading a CPI config, the stemcell will get associated with the matching CPI in the config, which in this case is `softlayer_ng`. One thing you can do to avoid this is to have the following `migrated_from:` block in your CPI config for the `softlayer_ng` CPI:

```
- name: sotflayer_ng
  type: softlayer
  migrated_from:
  - name: ""
```

Any subsequent uploads will correctly detect any assets previously associated with the default CPI of `""`.

At this point in time, we don't consider this behavior a bug. Please let us know if you have any other questions.

Best,
@jfmyers9 && @GarfieldIsAPhilosopher, CF BOSH

**Comment by mattcui** [comment]
@jfmyers9 We tried your approach, seems it didn't do anything after run `--fix` command, there is no change, we expect `softlayer-legacy` can be set there as the CPI and only one record for the stemcell.

```
Name                                     Version     OS             CPI               CID
bosh-bluemix-xen-ubuntu-trusty-go_agent  3468.17.2*  ubuntu-trusty  -                 1840873
```

**Comment by jfmyers9** [comment]
`bosh upload-stemcell --fix` is used for reuploading the bits of the stemcell in the IAAS/blobstore, not for updating it's database representation. Unfortunately, if you have already uploaded the stemcell without the CPI config, there is not currently a way to get the previous stemcell to show up with the updated CPI name.

Using `migrated_from:` will prevent there from being duplicate stemcell references. This also is only a temporary issue when migrating to a CPI config, as all subsequent stemcells that are uploaded will reference the correct CPI.

**Comment by mattcui** [comment]
Thanks, closing this issue
