### ISSUE TITLE
Do deployment addons support links?

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh#2061]
Originally posted [here](https://gist.github.com/Amit-PivotalLabs/c39528248b8cdc4ba8e347f8aa68abb6#gistcomment-2019675) by @abh1kg

----

> On the topic of BOSH links, do deployment addon jobs support links as well? I have a deployment manifest with an addon job defined. The release spec of one of the component jobs of the addon release defines a provides section. In the same manifest, I have several instance groups and component jobs which need to consume the links defined in the addon job.
I end up with an error as below:
> 
> ```
> Task 7912 | 17:16:37 | Preparing deployment: Preparing deployment (00:00:02)
>                      L Error: Failed to resolve links from deployment 'target-deployment'. See errors below:
>   - Failed to resolve link 'my_link' with type 'my_link_class' from job 'job' in instance group 'instance_group1'. Multiple link providers found:
>     - Link provider 'my_link' from job 'addon_job' in instance group 'instance_group1' in deployment 'target-deployment'
>     - Link provider 'my_link' from job 'addon_job' in instance group 'instance_group2' in deployment 'target-deployment'
> ```

**Comment by h4xnoodle** [comment]
Hi @abh1kg, thanks for giving this a try. The reason this doesn't work is because each instance group will end up providing the exact same link. Any release attempting to consume will need to somehow choose which one to use across all instance groups. 

At this time we don't support resolving links from addons. One work-around might be to include the addon as a job within the manifest for each instance group, and alias the providers for each. See the last part about resolving ambiguity here: https://bosh.io/docs/links/#overview

We will consider this in our next releases for BOSH.
