### ISSUE TITLE
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "ip_addresses_address_temp_key"

### ISSUE THREAD

**Issue by forexamplelyr** [cloudfoundry/bosh#2108]
When I deployed cf, I encountered these problems in turn.
1. ERROR -- DirectorJobRunner: Worker thread raised exception: Action Failed get_task: Task with id 5e9185cd-7060-4729-4a9f-2a9ee4472a4f could not be found
2.Action Failed get_task: Task c8f3bfb0-5b26-4c03-7cf4-d9031e20c571 result: Updating certificates with retries
3.Action Failed get_task: Task 26b818c2-fb11-4967-7681-09b534d045cf result: 1 of 2 post-start scripts failed. Failed Jobs: uaa. Successful Jobs: bosh-dns.
 
A strange thing is when I retry deploying，1-2ERROR can skip.

I think the following is the source of the error.
I get the following error deploying multiple dummy deployments in parallel ：
 ERROR -- DirectorJobRunner: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "ip_addresses_address_temp_key"
DETAIL:  Key (address_str)=(183763087) already exists.: (conn: 70036421836320) INSERT INTO "ip_addresses" ("address_str", "network_name", "task_id", "static", "instance_id", "created_at") VALUES ('183763087', 'default', '162', false, 20, '2018-12-22 08:18:36.681128+0000') RETURNING *
there are lots of ERROR such as this.

BOSH director (268.3.0) deployed with cloudfoundry/bosh-deployment and the following ops files:

bosh -e vbox -d cf deploy cf-deployment.yml \
     -o operations/bosh-lite.yml \
     -v system_domain=bosh-lite.com

So how can i deal with the problem??

**Comment by dpb587-pivotal** [comment]
The `ERROR`s you've found in `--debug` happen to be expected in this case - director uses try-catch logic around IP allocations in order to support concurrency with other deployments.

The original errors you'll want to look into were the failed tasks from the normal output:

 * `Task with id ... could not be found` probably means the agent (or VM) was unexpectedly restarted or crashed. Try again to see if its flakiness, otherwise see [these recommendations](https://bosh.io/docs/tips/#unreachable-agent) for a similar error.
 * `Updating certificates with retries` typically means the VM is underpowered; try using a slightly more powerful instance type.
 * `1 of 2 post-start scripts failed. Failed Jobs: uaa. Successful Jobs: bosh-dns` means the UAA job failed while it was starting up. You can find more details from the logs in `/var/vcap/sys/log/uaa/*`, possibly in the `post-start.*.log` files.

**Comment by forexamplelyr** [comment]
@dpb587-pivotal 
Thank you for your answer. There were no ERROR level log in /var/vcap/sys/log/uaa.log 
My friends tried to deploy vbox on a physical machine and then deployed cf, which was successful. So I suspect that the reason for these problems is because deploying cf can't re-vbox on a virtual machine with sufficient resources, and then deploy cf, so it always appears issue like: Action Failed get_task: Task c8f3bfb0-5b26-4c03-7cf4-d9031e20c571 result : Updating certificates with retries or Action Failed get_task: Task with id 5e9185cd-7060-4729-4a9f-2a9ee4472a4f could not be found
this is a related url：https://github.com/cloudfoundry/cf-deployment/issues/681

**Comment by dpb587-pivotal** [comment]
Sorry, but I don't follow what the current BOSH error you are facing. Can you restate what, single error you are now blocked on? Also please include the exact error output and steps you've already investigated.

**Comment by belinda-liu** [comment]
Hey @forexamplelyr, we're going to close this issue due to inactivity. Feel free to reopen if this is still a problem. Thanks!
