### ISSUE TITLE
Is there a way to not sync bosh dns domain entries in /etc/hosts

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh#2114]
After deploying `bosh-dns` and enabling `local-dns` feature on BOSH director, we noticed bosh-agent wiped out `/etc/hosts` and sync IP/domain (.microbosh) entries to the hosts file, in our case, there are some important domain entries we want to keep in `/etc/hosts`. So just wonder if there is a way to enable bosh-dns but don't sync to `/etc/hosts`? Thanks.

**Comment by dpb587-pivotal** [comment]
There's not currently a way to disable agent from overwriting `/etc/hosts`. It does it whenever it receives new `sync_dns` messages. The `/etc/hosts` was a very limited, first version of "BOSH DNS", but assuming bosh-dns has been adopted, it's not really needed anymore since bosh-dns answers the same hosts.

I think we should find a way to remove or disable agent's interference with `/etc/hosts`, possibly as opt-out behavior for a while. Do you have thoughts on how you would like to go about that, and would you be willing to contribute those changes to director/agent?

**Comment by maximilien** [comment]
@mattcui did you get an satisfactory answer? Should you close this?

**Comment by mattcui** [comment]
Some of our components still would like to leverage `/etc/hosts` to resolve the domain name, so it should be ok to keep the entries there for now, closing this issue.
