### ISSUE TITLE
BOSH will always download 'bosh-dns-aliases' release during a deployment

### ISSUE THREAD

**Issue by aemengo** [cloudfoundry/bosh#2142]
No matter how many times I deploy cf-deployment (with no changes), the `bosh-dns-aliases` release keeps getting re-downloaded, no matter the IAAS. This is troublesome for deploys in offline environments.
Currently observed on [cf-deployment](https://github.com/cloudfoundry/cf-deployment): `v7.5.0`.

<img width="470" alt="screen shot 2019-02-21 at 8 15 34 am" src="https://user-images.githubusercontent.com/4236888/53186677-78a39680-35cf-11e9-8d30-007814c91e69.png">

**Comment by dpb587-pivotal** [comment]
This is likely due to `bosh-dns-aliases` not having any packages. When checking for needed uploads, CLI asks director what source/compiled versions it already has and, if it doesn't find a compiled package for the stemcell, it re-uploads it.

@heyjcollins, I'd recommend that cf-deployment stop trying to compile the `bosh-dns-aliases` release. It has no packages needing to be compiled (it's essentially a no-op `export-release` for you today), and I think it'd happen to fix this particular example, too.

@aemengo, if you're interested in broader discussion around this behavior for contexts other than cf-deployment, I'd recommend creating a new issue in [bosh-cli](https://github.com/cloudfoundry/bosh-cli).

**Comment by aemengo** [comment]
Closed in favor of: https://github.com/cloudfoundry/bosh-cli/issues/518
