### ISSUE TITLE
Auth error during release download results in digest error

### ISSUE THREAD

**Issue by KaiHofstetter** [cloudfoundry/bosh#2153]
**Describe the bug**
If `create-env` cannot download a release because of an authentication error, BOSH calculates the digest and fails with a digest error. BOSH doesn't show the actual authentication error.
The digest error is misleading.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Use a release url in the BOSH manifest, which is password secured.
2. Deploy a bosh director on any IaaS

**Expected behavior**
BOSH shouldn't calculate the digest and should show an authentication error.

**Logs**
```
Started validating
  Downloading release 'bosh'... Failed (00:00:02)
Failed validating (00:00:02)

Failed to download from 'https://username:password@repo.io:443/.../release.tgz':
  Verifying digest for downloaded file:
    Expected stream to have digest '3e37786c9dcb0a73a34ee55c89b3a43d84e72c25' but was 'da39a3ee5e6b4b0d3255bfef95601890afd80709'
```

**Versions (please complete the following information):**
 - BOSH v268.6.0
 - BOSH CLI v5.4.

@langered

**Comment by voelzmo** [comment]
side note: this is true for any error response code, regardless of the reason. Most likely because the response code isn't checked here: https://github.com/cloudfoundry/bosh-cli/blob/a18c72307483843b5e190c383ff5e6835b3a8bf2/installation/tarball/provider.go#L124 but the golang httpclient doesn't throw errors on no-2xx responses: https://golang.org/pkg/net/http/#Client.Get
