### ISSUE TITLE
Improve messaging for retrieving stemcell

### ISSUE THREAD

**Issue by shamus** [cloudfoundry/bosh#2159]
**Is your feature request related to a problem? Please describe.**
Doing a bosh deploy for the first time, I'm prompted to get a stemcell with this message
> Error: Stemcell with Operating System 'ubuntu-xenial' doesn't exist

If I'm familliar with bosh, I know to go to https://bosh.io and find it.  But actually I'm not familliar with bosh and my pair helped me out.

**Describe the solution you'd like**
What if bosh told me where to find the stemcell, instead of my pair.  :)

**Describe alternatives you've considered**
Even cooler might be if it offered to download the stemcell for me.

**Comment by mrosecrance** [comment]
I suppose from my perspective there are potentially a number of places you could get stemcells (bosh.io being only one of them). It wouldn't be a large change to include in the output message but so far we haven't mentioned bosh.io in any cli output as far as I know.

Downloading a stemcell automatically would require more thought. To download it for you we would have to assume you:
1. Have an outbound internet connection
2. Know your IAAS that you need the stemcell for (which since multi-cpi is a thing may mean all the IAAS's).

**Comment by voelzmo** [comment]
There is auto-downloading for releases, though, in case you define remote URLs: https://bosh.io/docs/manifest-v2/#releases
A similar mechanism could work for stemcells as well, right? I think in the days of the ruby CLI it did work, although implemented on the client side. Not sure how many people would want to use this in production-systems, but it would definitely make for a better kicking-the-tires experience

**Comment by mrosecrance** [comment]
I actually really like that idea. The bosh manifest author still would need to do the picking of the version and OS which removes a lot of my concerns.  Floating stemcells could be done by not specifying a specific version which may help people stay on top of latest stemcell patches.

**Comment by voelzmo** [comment]
> Floating stemcells could be done by not specifying a specific version which may help people stay on top of latest stemcell patches.

I'm not sure how/if this would work given you would have to specify a sha for the downloaded artifact. At least this would require user interaction on every stemcell update – potentially very unexpected for the uninitiated user.

**Comment by mrosecrance** [comment]
As far as I know sha is optional on both releases and stemcells. I was imagining this happening similar to `bosh upload-stemcell https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent` which uploads the latest release on bosh-io. I have no idea if there is demand for "floating" releases on deploy so it might be a nice-to-have rather than a key feature

**Comment by h4xnoodle** [comment]
> I suppose from my perspective there are potentially a number of places you could get stemcells
 
There are many places to get stemcells, and automatically downloading from somewhere, or having that all be configured, would add a lot of work. 

Users of Bosh obtain stemcells from their own local machines (custom built), bosh.io (open-source users, whoemever), within licensed and permission-controlled locations. 

Closing this issue as there are many ways to obtain a stemcell, and we wouldn't want to mislead by choosing one place to suggest one. Apologies for the vagueness of where stemcells come from!
