### ISSUE TITLE
director job doesn't read "director.cpi_job" property input

### ISSUE THREAD

**Issue by donghoang89** [cloudfoundry/bosh#2164]
**Describe the bug**
After deploying bosh director to google cloud, I can't upload stemcell to the director. Even though I input the value of "director.cpi_job" to be "google_cpi", bosh director still look for cpi at "/var/vcap/jobs/gcp_cpi/"

**To Reproduce**
Steps to reproduce the behavior (example):
1. Deploy a bosh director (manifest and api files attached 
[my-bosh-manifest.yml.txt](https://github.com/cloudfoundry/bosh/files/3004664/my-bosh-manifest.yml.txt)
[my-bosh-cpi.yml.txt](https://github.com/cloudfoundry/bosh/files/3004665/my-bosh-cpi.yml.txt)
)
```
bosh create-env my-bosh-manifest.yml -o my-bosh-cpi.yml               --state=my-bosh-state.json               --vars-store=my-bosh-creds.yml
```
2. Attempt to upload stemcells
```
 04:02 PM:~/guiderails/gems/calculi_terra $ bosh -e my-bosh -n --config=my-bosh.yml upload-stemcell --sha1 7776aa4e29e3a2397f9ef8b827744d829cc32430 bosh-google-kvm-ubuntu-trusty-go_agent?v=3586.25
Using environment '10.3.0.10' as client 'admin'

########################################################## 100.00% 14.11 KB/s 1s
Task 2

Task 2 | 23:03:13 | Update stemcell: Extracting stemcell archive (00:00:00)
Task 2 | 23:03:13 | Update stemcell: Verifying stemcell manifest (00:00:00)
Task 2 | 23:03:13 | Error: Failed to run cpi: '/var/vcap/jobs/gcp_cpi/bin/cpi' is not executable

Task 2 Started  Fri Mar 22 23:03:13 UTC 2019
Task 2 Finished Fri Mar 22 23:03:13 UTC 2019
Task 2 Duration 00:00:00
Task 2 error

Uploading stemcell file:
  Expected task '2' to succeed but state is 'error'

Exit code 1
````

**Expected behavior**
```
 09:45 AM:~/guiderails/gems/calculi_terra $ bosh -e my-bosh-n --config=my-bosh.yml upload-stemcell --sha1 7776aa4e29e3a2397f9ef8b827744d829cc32430 bosh-google-kvm-ubuntu-trusty-go_agent?v=3586.25
Using environment '10.3.0.10' as client 'admin'

########################################################## 100.00% 16.79 KB/s 1s
Task 34

Task 34 | 16:45:18 | Update stemcell: Extracting stemcell archive (00:00:00)
Task 34 | 16:45:18 | Update stemcell: Verifying stemcell manifest (00:00:00)
Task 34 | 16:45:18 | Update stemcell: Checking if this stemcell already exists (cpi: gcp) (00:00:00)
Task 34 | 16:45:18 | Update stemcell: Uploading stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.25 to the cloud (cpi: gcp) (00:01:59)
Task 34 | 16:47:17 | Update stemcell: Save stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3586.25 (stemcell-2f57e9ad-9f6b-4f60-7ac1-2a5a30fdf568) (cpi: gcp) (00:00:00)

Task 34 Started  Mon Mar 25 16:45:18 UTC 2019
Task 34 Finished Mon Mar 25 16:47:17 UTC 2019
Task 34 Duration 00:01:59
Task 34 done

Succeeded
```

**Logs**
Logs are always helpful! Add logs to help explain your problem.

**Versions (please complete the following information):**
- bosh-cli version: version 2.0.48-e94aeeb-2018-01-09T23:08:08Z
- bosh-release version: 266.4.0
- cloud: gcp
- stemcell: bosh-google-kvm-ubuntu-trusty-go_agent/3586.25

**Deployment info:**

**Additional context**

**Comment by donghoang89** [comment]
Thank you for your response.

Currently we are having to work around this by creating a supporting boshrelease, which softlink /var/vcap/jobs/google_cpi with /var/vcap/jobs/gcp_cpi

**Comment by mrosecrance** [comment]
This seems like a really odd error to me as the job on the google cpi has been called `google_cpi` for several years now and we've managed to upload plenty of stemcells to gcp since then. If you're happy with the work around, do you want to close the issue or I have some other thoughts on how to go about digging into this.

Is there anything special in `my-bosh.yml`? Does the more generic command `bosh upload-stemcell --sha1 8108d482c10bac03ce2cfd97f7f6765877cc0026 \
  https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent?v=3586.93` give the same error?

Another thought is that there could be a configuration issue, in which case we should probably provide a better error message.

To verify this: does this issue still occur when deploying with [BOSH Bootloader](https://github.com/cloudfoundry/bosh-bootloader). It terraforms a lot of the dependencies that would otherwise need to be done manually. Instructions [here](https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/getting-started-gcp.md).

**Comment by belinda-liu** [comment]
Hi @donghoang89,

Are you still experiencing this issue? This seems like perhaps your director was initially deployed with an incorrect `gcp_cpi` and was not updated in your subsequent create-env with the `my-bosh-cpi.yml` ops-file. I would recommend doing a clean deploy of your director and ensuring that the CPI is updated as a sanity check.
If this is no longer a problem you're seeing, we'd like to close this issue.

**Comment by ssapra** [comment]
Closing issue since there's been no update.
