### ISSUE TITLE
Bosh leaking functions between templates

### ISSUE THREAD

**Issue by charleshansen** [cloudfoundry/bosh#2181]
For context https://github.com/cloudfoundry/capi-release/issues/141

Bosh is leaking functions between templates on master. I think we are often reusing evaluation contexts after this PR https://github.com/cloudfoundry/bosh/pull/2147/files It isn't clear if we were leaking functions before that time. It might be worth investigating.

**Comment by voelzmo** [comment]
Seems like the change which introduced usage of `yaml_escape` in the template of `capi-release/jobs/cc_deployment_updater/templates/cloud_controller_ng.yml.erb` was one in summer of 2018: https://github.com/cloudfoundry/capi-release/commit/3cdbcb87ec9ac5ad6b7e62f06b712d8bad352218

Deploying this release seems to have worked ever since, so it is likely that PR #2147 didn't introduce this behavior.

**Comment by charleshansen** [comment]
Just for kicks, I reproduced the issue on `268.2.0` and it is still there, so looks like you are right, it isn't #2147. I don't understand the exact mechanism for how these functions are escaping, I would think they should be defined in the EvaluationContext, and those weren't re-used before the PR, so they must be defined somewhere else.
