### ISSUE TITLE
bosh-aws-xen-hvm-ubuntu-xenial-go_agent stemcell doesn't contain proper DNS search domain

### ISSUE THREAD

**Issue by sebarys** [cloudfoundry/bosh#2223]
**Describe the bug**

After upgrade from `456.x` to `621.x` line of `bosh-aws-xen-hvm-ubuntu-xenial-go_agent` stemcell we noticed issues with resolving hostnames that are not FQDN.
It looks that the newest stemcell versions missing `search ec2.internal` search domain entry in `/etc/resolv.conf`

**To Reproduce**
On instance based on `bosh-aws-xen-hvm-ubuntu-xenial-go_agent 456.74`:
```
$ cat /etc/resolv.conf
nameserver 10.100.0.2
search ec2.internal
```
On instance based on `bosh-aws-xen-hvm-ubuntu-xenial-go_agent 621.5`:
```
$ cat /etc/resolv.conf
nameserver 10.100.0.2
```

**Expected behavior**

hostnames pointing to other internal EC2 instances will be resolved properly.

**Comment by aashah** [comment]
Hey @sebarys,

You may have omitted this because it's simple, but can you make sure that those are all the contents of `/etc/resolv.conf`? The bosh-agent usually leaves a line [at the top](https://github.com/cloudfoundry/bosh-agent/blob/a5a6aebe7d6455bf86c8217283db4e7c3ff245b5/platform/net/ubuntu_net_manager.go#L463) saying `Generated by bosh-agent`. 

I'm wondering if there is something else at play here that I'm not seeing.

- Aakash

**Comment by sebarys** [comment]
Hi @aashah!

I don't have wide knowledge in this topic, but I can easily reproduce issue with resolving not FQDN.
With `bosh-aws-xen-hvm-ubuntu-xenial-go_agent 456.74` stemcell:
```
$ nslookup ip-10-59-1-15
Server:        10.100.0.2
Address:    10.100.0.2#53

Non-authoritative answer:
Name:    ip-10-59-1-15.ec2.internal
Address: 10.59.1.15

$ nslookup ip-10-59-1-15.ec2.internal
Server:        10.100.0.2
Address:    10.100.0.2#53

Non-authoritative answer:
Name:    ip-10-59-1-15.ec2.internal
Address: 10.59.1.15
```

With `bosh-aws-xen-hvm-ubuntu-xenial-go_agent 621.5` stemcell:
```
$ nslookup ip-10-59-1-15
Server:        10.100.0.2
Address:    10.100.0.2#53

** server can't find ip-10-59-1-15: NXDOMAIN

$ nslookup ip-10-59-1-15.ec2.internal
Server:        10.100.0.2
Address:    10.100.0.2#53

Non-authoritative answer:
Name:    ip-10-59-1-15.ec2.internal
Address: 10.59.1.15
```

**Comment by jfmyers9** [comment]
Hi @sebarys 

We believe that we have found the root cause of the issue. We are hoping to get this change into the 621 stemcell line ASAP. Thanks for reporting the bug.

For context, we needed to enable the `UseDomains=yes` option in the systemd networking configuration. This issue was only present on the 621.x stemcell line because earlier stemcell lines were not relying on systemd networking.

Let us know if you have any other questions.

Best,

@jfmyers9 && @alex-slynko, CF BOSH

**Comment by alex-slynko** [comment]
Hi @sebarys 
The 621.51 stemcell has a fix. Please check that it works for you.

**Comment by sebarys** [comment]
Hi,
Thanks for letting us now!
For now I've added `os-conf` release to our deployments with `resolv` job:
```
- name: resolv
    release: os-conf
    properties:
      search: eu-central-1.compute.internal
```
and it works as workaround. I will let you know when we will use newer stemcell.
