### ISSUE TITLE
Upgrading the bosh to latest release

### ISSUE THREAD

**Issue by spanwar12** [cloudfoundry/bosh#2301]
Hi Team,

I have the following questions for upgrading the bosh to latest release:
1. Can i directly go to 271.8.0 bosh release version from 270.11.3 and 270.4.0 bosh releases or do i need to go through intermediate releases ?
2. What is the bosh cli version i will get from 271.8.0 bosh release version ?
3. Will the fixes from previous releases will be included in this latest bosh version i.e 271.8.0 ?
4. Any dependencies on 271.8.0 ?
5. Do we have any breaking changes with 271.8.0 ?

**Comment by spanwar12** [comment]
Any update on my query ?

**Comment by klakin-pivotal** [comment]
1) You should be able to go directly from one version of the Bosh Director to another. There should be no need to go through intermediate releases.
2) The Bosh CLI is a separate project that is released and versioned independently of the Bosh Director. You can find it here: <https://github.com/cloudfoundry/bosh-cli>
3) Bug fixes resolved in an older major version should be fixed in newer major versions of the Director, when appropriate.
4) I'm not sure what you're asking with this question.
5) The release notes for the Bosh Director are the place to look for any breaking changes: <https://github.com/cloudfoundry/bosh/releases>

Additionally, we spend most of our time in Slack, so you'll get faster response time if you ask your question in the `#bosh` channel in the Cloudfoundry Foundation Slack server: <https://slack.cloudfoundry.org>. This alternative, along with a couple of others are mentioned in this repo's `README`: <https://github.com/cloudfoundry/bosh>

**Comment by spanwar12** [comment]
Thanks Klakin .
