### ISSUE TITLE
typo in update-config error message

### ISSUE THREAD

**Issue by hongtaiwang** [cloudfoundry/bosh#2308]
**Describe the bug**
when trying to update a cloud config using a client with insufficient authority, an error like `Director responded with non-successful status code '401' response '{"code":600000,"description":"Require one of the scopes:..."}' ` will occur. the `scopes` here should be authorities instead.

**To Reproduce**
Steps to reproduce the behavior (example):
1. create a cloud config with team '-'
2. bosh update-config with another client with another team

**Expected behavior**
The error message should be Require one of the **Authorities**

**Logs**
```
kubo@jumper:~$ bosh update-config --type cloud --name pivotal-container-service-eb45008f33c2165d78c8 pks-cloud-config.yml
Using environment '88.0.0.3' as client 'pivotal-container-service-eb45008f33c2165d78c8'
Fetching diff result:
  Director responded with non-successful status code '401' response '{"code":600000,"description":"Require one of the scopes: bosh.admin, bosh.b2c1d6be-34ad-4bdf-8479-7396a41abd92.admin"}'
Exit code 1
```

**Versions (please complete the following information):**
 - Infrastructure: vsphere
 - BOSH version 2.10.11-build.222
 - BOSH CLI version 6.1.1
 - Stemcell version ubuntu-xenial 621.125
 - ... other versions of releases being used (BOSH DNS, Credhub, UAA, BPM, etc)

**Deployment info:**
If possible, share your (redacted) manifest and any ops files used to deploy
BOSH or any other releases on top of BOSH.

If you used any deployment strategy it'd be helpful to point it out and share as
much about it as possible (e.g.  bosh-deployment, PCF, genesis, spiff, etc)

**Additional context**

**Comment by klakin-pivotal** [comment]
Hey, are you sure that these should be called `Authorities`, rather than `Scopes`? The documentation appears to call these things Scopes: <https://bosh.io/docs/director-users-uaa-scopes/#top-level-scopes>

The OAuth RFC doesn't mention Authorities at all, and -from what I can tell- an `Authority` is a UAA concept used to describe a `Scope` that was granted to an authorized robot.

**Comment by klakin-pivotal** [comment]
Actually, forget about those questions. I have read the Slack thread that prompted this Github Issue.

I'll do some digging to see where this message is coming from, and if it's reasonably easy to improve it.

**Comment by lnguyen** [comment]
Hey @hongtaiwang we looked into this and for uaa clients authorities is used because it is assumed by UAA. Closing as this is nuance of UAA that returning authorities as scopes, refer [here](https://docs.pivotal.io/application-service/2-8/uaa/uaa-concepts.html#autoapprove ). We've updated bosh docs to show use of `--authorities` instead of `--scope` when adding bosh teams.
