### ISSUE TITLE
Running errands on stopped VMs is a valid scenario

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh#2349]
**Describe the bug**
The change https://github.com/cloudfoundry/bosh/pull/2339 preventing an errand to run on stopped VMs shipped with https://github.com/cloudfoundry/bosh/releases/tag/v271.17.0 is a breaking change. We've a scenario for a service deployment, where a co-located errand would restore the database after the processes have been stopped with `bosh stop`. We had to downgrade the Director to v271.16.0. The scenario might be less relevant for not co-located errands or hard stopped instances.

**To Reproduce**
Steps to reproduce the behavior (example):
Well this requires a specific release of course, but it should be clear from the description.

**Expected behavior**
Don't prevent to run errands against a stopped instance.

**Logs**
-
**Versions (please complete the following information):**
 - Infrastructure: all
 - BOSH version 217.17.0

**Comment by mrosecrance** [comment]
The issue we were intending to fix is this:
1) bosh stop the vm
2) forgot about it and deploy more changes -> some jobs are now missing from the stopped vm
3) run an errand
4) see errors since the errand is expecting missing jobs on the older stopped vm

Can you share more details on why bosh stop is used as a regular flow? It may not be specifically relevant to this conversation but I think there's a pattern of usage here that I'm not familiar with.

This could potentially be added as a flag on run-errand like `--include-stopped` going forward

**Comment by friegger** [comment]
@anoopjp Can you elaborate a little why it is implemented like it is?

@mrosecrance How much effort would it be to bring in such a flag? I still believe that running an errand on stopped jobs is a valid scenario.

**Comment by mrosecrance** [comment]
It wouldn't be much effort but would mean we need a new bosh-cli. Is this something SAP has bandwidth to PR? 

We did this because we got a few reports of broken deployments and unexpected behavior but since this is a case you all use, I think it makes sense to support it (I would still argue with a flag rather than as default behavior though)

**Comment by friegger** [comment]
@mrosecrance Yes, we would be able to provide this at some point in time. The flag would need to be represented in the [API](https://github.com/cloudfoundry/bosh/blob/b21cafff8aa969645bc771a76f6a51cddd7ba108/src/bosh-director/lib/bosh/director/api/controllers/deployments_controller.rb#L503) as well and handed to the job wouldn't it?

I first would like to understand from @AnoopJP whether this would be something they could adopt easily.

**Comment by anoopjb** [comment]
As @friegger said, [Service Fabrik](https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/91097585e13bdfe6717963c0e519962bea240c50/broker/applications/operators/src/bosh-restore-operator/BoshRestoreService.js#L24) is affected by this change. We have a `cf start-restore`  plugin. The restore operation uses a previously backed up snapshot to create a volume and uses it in the deployment. The restore flow is,

1. Stop the bosh deployment
2. Create disk for restore
3. Attach disk to bosh deployment
4. Hooks via bosh errands.
5. Start the bosh deployment

The new disk has the backed up data. The service may need some changes to the data before starting the program.
This is achieved using the errands. An example is the decompressing of archived data during restore of a PostgreSQL instance.

**Comment by bgandon** [comment]
Thank you for clarifying the expected behaviour @anoopjb. But stopped VMs are also skipped when the rest of the deployment is updated. This could lead to executing old errand code (old jobs, old packages) and reach unexpected or very strange behaviours.

(We've recently hit an issue with the Bosh team, where a stoped VM keeps a relation in the Bosh SQL database, with a Bosh Release that is no more used by the rest of the deployment after some update, leading to Foreign Key 500 errors in the API.)

This means that the semantics behind stopped VMs need to be clarified.

So far the problem I can see is that updating a stopped VM cannot verify that the update is actually successful because the jobs are not run. Usual semantics with successful `bosh deploy` is that all running VMs are starting up successfully, which gives some guarantees to the operator that things are fine.

The new semantic we could establish is that stopped VMs are updated (if “softly” stopped only) and assumed as being successful even if this has not been verified, delaying the findings of any issues for later when the VMs are started. We also need to establish similar and consistent semantics with hard-stopped VMs.

This would have several impacts in the Director implementation, but currently we are in an “under-defined” zone where local behaviour changes will lead to more issues if we don't take a step back and clarify the fundamental Bosh semantics that are at stake.

Any feedback from other members of the Bosh team about this?

**Comment by rkoster** [comment]
@anoopjb Thanks for sharing your usecase, however I think it would be better to deal with service management from within the errand itself and not rely on external orchestration of `bosh stop / start`. This is for example also the pattern that other releases use:
- https://github.com/cloudfoundry/cf-mysql-release/blob/develop/jobs/rejoin-unsafe/templates/errand.sh.erb#L14
- https://github.com/cloudfoundry/cf-mysql-bootstrap/blob/master/bootstrapper/bootstrapper.go
- https://github.com/cloudfoundry/pxc-release/blob/master/jobs/bootstrap/templates/errand.sh.erb
- https://github.com/cloudfoundry/cf-mysql-bootstrap/blob/master/bootstrapper/bootstrapper.go#L32

**Comment by friegger** [comment]
We'll have a discussion with @anoopjb to clarify what effort it would be for Service Fabrik to adopt the proposed changes.

**Comment by friegger** [comment]
Unfortunately, this is still a blocker for us. Let's discuss options in tomorrows WG meeting.

**Comment by friegger** [comment]
We will work on a flag that provides backwards compatibility with a deprecation warning.

**Comment by friegger** [comment]
Proposed property:
```
director.allow_errands_on_stopped_instances (default: false)
```

**Comment by FlorianNachtigall** [comment]
Proposed PR to introduce the director property #2374

**Comment by FlorianNachtigall** [comment]
Closing this issue as the PR https://github.com/cloudfoundry/bosh/pull/2374, which implements the discussed functionality, has been merged.
