### ISSUE TITLE
Deploy slow-to-install addon before other releases

### ISSUE THREAD

**Issue by Justin-W** [cloudfoundry/bosh#2365]
**Is your feature request related to a problem? Please describe.**

We have an environment where all VMs must have certain "upon VM provisioning" setup automation executed (which enables the VMs to be able to access intranet resources), and that automation must finish before other (non-addon) releases get installed.

Configuring the startup release as a Bosh [addon](https://bosh.io/docs/terminology/#addon) in the [runtime config](https://bosh.io/docs/runtime-config/#addons) seems perfect, except the startup release is slow to complete (over 10 mins), and I can't find any way to configure that a specific addon (or even "all addons") should finish installing _before_ any other releases start installing.

**Describe the solution you'd like**

_If_ addons already install before non-addon releases, then problem solved. (I couldn't find any docs which define the current behavior.)

_If not_ (i.e. if addons and non-addons install in parallel), then I'd like to be able to configure (in the runtime config) that 1 specific addon and/or all addons must be installed before other releases start installing. Basically, we need this 1 addon to be configured (within the runtime config) as a dependency of any other releases on the VM, _without_ modifying every other releases and/or the deployment manifests.

We also need to be able to override the default (5 minute) and/or deployment manifest-specified timeouts for this release (again, without modifying the other releases or any deployment manifests), so that the >10 minute install time of this addon will be treated as an exception to the default or manifest-specified timeouts.

**Describe alternatives you've considered**

Modifying every other release and/or the deployment manifest to make the addon an explicit dependency would solve the sequential install, but is not a feasible solution, since it completely prevents reuse of existing bosh releases.

Embedding the setup addon's functionality into a custom stemcell also isn't feasible, since the automation _must_ be executed on _each_ VM (upon VM provisioning, not beforehand), and should be able to be updated (or not) independent of releasing new stemcells.

**Additional context**

* [monit default timeout](https://mmonit.com/monit/documentation/monit.html#Program)

**Comment by Justin-W** [comment]
This is a high priority feature for us.

If this feature is possible but not yet supported, we'd be happy to work on the implementation, if someone could give us some guidance on where/how to start.

**Comment by bgandon** [comment]
Addons are only a source for bringing co-located Bosh jobs, that is transverse to all Bosh deployments managed by a given Bosh Director. No difference with release jobs brought by any deployment manifest. That's why [the job lifecycle docs](https://bosh.io/docs/job-lifecycle/) don't mention any difference between Addons and Deployment jobs. They are basically the same in nature.

So the way Bosh works stays simple: all jobs are deployed in parallel, following [the job lifecycle documented in the docs](https://bosh.io/docs/job-lifecycle/). That is to say, all `pre-start` scripts run in parallel with no timeout, and after they are done and successful, then jobs are all started in parallel with `monit start`. When all jobs startups are fine, then `post-start` scripts are run in parallel.

The concern you're raising is very classical. Pre-start scripts that don't know eachother can't wait for eachother. There is nothing "above" (or external) to those that would implement some priority in their execution. Same for jobs startup. This is a common issue with Docker engine that requires to be running before anything else tries to run any Docker image. In some Bosh releases, the Docker engine is started by a `pre-start` script and Docker images by `monit start`. With some other Release design, the engine starts in the `monit start` phase, and images are run in the `post-start` phase.

Back to your concerns, I would suggest those best practice for you:
- Your "slow to complete" addon setup should be implemented in the `pre-start` phase. It would fit nicely because of the freedom you have there with timeouts. But you would need to implement some adjusted timeout anyway, so that any infinite loop is prevented. Freezing forever is always a possible issue to consider and to prevent from. This timeout should be configurable so that runtime operators can tweak it for non-prod environments running with lower resources and thus requiring more time to complete.
- Any other Bosh release that requires the "slow setup" (and access intranet resources) in any `pre-start` script, should implement specific wait loops in the affected `pre-start` scripts, so that the code executes after the access to intranet resources is fine. By the way, you didn't mention if any is affected in this regard.
- When other Bosh release are waiting for proper access to intranet resources, they should implement some timeout in case something freezes somewhere and access is eventually never enabled for some reason. This timeout should be configurable, so that it can be reduced down to zero in scenarios where "intranet resources" are immediately reachable.

Don't hesitate to fork other people releases, and submit back PR to them with your improvements. Your additions can be made optional. As long as you provide automated tests for those, people should just be fine with your features.

**Comment by rkoster** [comment]
Just wanted to point out the way that the bosh DNS release addresses this problem, by providing a [wait script](https://github.com/cloudfoundry/bosh-dns-release/blob/master/jobs/bosh-dns/templates/wait.erb) for other releases to call, which hangs until the service has been started.

**Comment by Justin-W** [comment]
@bgandon @rkoster Thank you very much for the suggestions. We're going to give that approach a try, so I'll close this for now. Much appreciated.
