### ISSUE TITLE
Proposal: Cache "bosh ssh" gateway settings for each target bosh

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#305]
Once "bosh ssh --gateway-host/port/idenity-file" has been used, cache these settings in ~/.bosh_config for that target bosh/microbosh. Assumes that each bosh would have a different gateway; but use the same gateway for all its deployments.

Related to https://github.com/cloudfoundry/bosh/pull/302

**Comment by axelaris** [comment]
Also it could be nice to keep default value for long settings like `--strict_host_key_checking <yes/no>` somewhere in the `.bosh_config`
It's very uncomfortable to type that option every time.

**Comment by bosh-ci-push-pull** [comment]
With newer stemcells (3093+) strict_host_key_checking is not necessary
because CLI knows which host key is expected and trust it. You have to
update your CLI, Director and stemcells for this to take the effect.
bosh-lite stemcells are not available yet for that version, but we are
working on it.

Regarding gateway: We decided to make default gateway settings a director
configuration. CLI will see them and use the gateway without having user
specify any of the gateway options. Story for this:
https://www.pivotaltracker.com/story/show/104125746

**Comment by drnic** [comment]
Cool re default gateway settings.

**Comment by cppforlife** [comment]
As of bosh v217, the Director can be configured with default ssh settings: https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=217#p=director.default_ssh_options
