### ISSUE TITLE
[stemcell] network access denied; how to enable?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh#547]
I want to create stemcells that pull down non-apt assets during some additional stages. Currently the `rake stemcell:build` task is blocking public internet access some how. If I add `http_proxy=http://localhost:3142` then apt-get commands work (I assume from a local cache outside of the chroot).

How do I allow other http traffic to continue out to the internet?

**Comment by dpb587-pivotal** [comment]
Closing - stemcell execution environment has changed quite a bit since this was created and I doubt it's still an issue. Hopefully you're not needing to create custom stemcells anymore. If so, would like to hear why and if they can be done in a release instead of further stemcell sprawl; or feel free to create an issue in the new stemcell repo, [cloudfoundry/bosh-linux-stemcell-builder](https://github.com/cloudfoundry/bosh-linux-stemcell-builder).
