### ISSUE TITLE
Restarting a statically networked vm with Openstack nova loses MTU configuration

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh#911]
**Problem description**
When you use GRE tunnels as plugin for neutron, the MTU of your network devices needs to be set to `1500` instead of the default `1492`, otherwise packets will get dropped by neutron.

The MTU is set by Openstack over DHCP when the machine boots up, even if you you use static networking for that machine [1]. This setting is not persisted by the agent, e.g. for ubuntu it belongs in the `/etc/networks/interfaces` [2].

That means, if you restart the VM, e.g. by calling `nova reboot`, the MTU defaults back to 1492 and packets get dropped.

**Proposed solutions**
Settings received over the Openstack DHCP service which are not contained in the seetings the bosh agent received should probably also be persisted in the network configuration. For now, that involves MTU, but I could see other properties here as well - Openstack has a lot to offer here :)
Another example is additional gateway configurations set for individual IPs by the Openstack DHCP server.

**Question**
Should we try to persist the MTU received from the DHCP service as well? What shall we do about more complicated things, such as additional gateways for individual IPs?

[1] https://github.com/cloudfoundry/bosh/blob/master/stemcell_builder/stages/bosh_openstack_agent_settings/apply.sh#L19
[2] http://manpages.ubuntu.com/manpages/precise/man5/interfaces.5.html

**Comment by cppforlife** [comment]
Im a bit confused. Do you mean the other way: 1492 is required and 1500 is set? Where is 1492 default coming from?

We've recently switched back to using DHCP for manual networks on OpenStack unless you opt out: https://github.com/cloudfoundry/bosh/commit/ee3bf7a1814f17b7f6d23a7c91c75674dbe9c215 and https://github.com/cloudfoundry/bosh-agent/commit/533ac3615acf55775502238479c2c9dc28e135db. Now CPI can specify `use_dhcp` to tell agent to use DHCP for that specific network. For AWS CPI it always set it.

Btw NetworkingType is no longer used since agent is smart enough to pick what to do: https://github.com/cloudfoundry/bosh-agent/blob/master/infrastructure/settings_source_factory.go#L14

**Comment by voelzmo** [comment]
Yeah, sorry it is actually the other way around: The Openstack DHCP server configures the MTU to something like 1476 or even a bit less. That is necessary because tunneling over GRE tunnels adds an overhead of 24 bytes. 

After a restart, the machine defaults to an MTU of 1500 which results in non-functional overlay network.

About those two changes you referred to:
Does that mean I can do manual networking, use static IPs, set `use_dhcp: true` and the DHCP server will assign the IP which I specified and additionally all other DHCP properties coming from Openstack, such as MTU and additional routes?

**Comment by voelzmo** [comment]
As far as I can tell there is no newer release than version 9 for the [openstack-cpi](http://bosh.io/releases/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release) so that functionality is not ready for consumption yet, right? I'll try to create my own final release and test if that fixes the problem

**Comment by voelzmo** [comment]
The new `use_dhcp` property works perfectly, thanks! Now we got all the settings we would like to see and they survive reboots as well.
