### ISSUE TITLE
CHANGELOG / release notes missing

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/bosh#959]
Hi,

I see that CHANGELOG.md file was not updated since 2941 and I also don't see any release notes with many of the releases (ever since v141, with recent v206 being exception). On some other web side I found a link to BOSH changelog, but which just pointed to git diff between the given and previous release - this is not so useful and human readable as the usual release notes. 

Is there any reason you have stopped updating CHANGELOG? Release notes are very useful for BOSH operators to help them understand what changes have been made, which helps them decide when and how to upgrade...

**Comment by bosh-ci-push-pull** [comment]
I'm planning to switch to using GitHub releases to better keep track of that. Already added release notes for 3074.

**Comment by mtekel** [comment]
Where are those release notes? I can only see v206/3072 notes, but for 3074 there's nothing. Curiously, CF v218 release notes dissappeared recently...

**Comment by cppforlife** [comment]
Oops I meant 3072. Added 3074... 

re cf-release: I believe it's still a draft /cc @Amit-PivotalLabs

**Comment by mtekel** [comment]
thanks

**Comment by mtekel** [comment]
3202 release notes missing again. Is it that hard? Just make it mandatory for your release process. Changelog.MD has last update 2 months ago...

**Comment by cppforlife** [comment]
look at github releases tab. it says that in the changelog.md. some builds dont include details since they may only contain internal changes or unannounced features that will be announced later when necessary fixes (remaining features) are included.

**Comment by mtekel** [comment]
I have decided to not use that release, since no notes means there could be a breaking change or anything. It looks like the notes were forgotten. I simply wouldn't assume "no notes" = safe. Also, unannounced or disabled features = no reason to upgrade. Why make such releases?

**Comment by cppforlife** [comment]
@mtekel may be i need to adjust which details get shared as part of the release. right now started but not complete features are left out of release notes to avoid confusion of them being done. i typically note them once they are complete and verified by few internal consumers after a few releases (e.g. upcoming uaa team scopes). 

since we are working on different features in parallel, they progress differently (some are started, almost done, just completed, etc.). we also typically avoid branch-per-feature given that makes it harder to refactor (we do occasionally use longer running branch for a bigger/riskier feature). so as a result each build that comes out of a CI has a combination of finished, in progress, etc. features. 

we releases those builds for all different types of consumers: some teams pull them in via ci automatically, some pick specific builds for specific features, etc. that way we get faster feedback for certain features without trying to finish it, but not necessarily announcing it to everyone.

i'll try to include more "hidden/internal-ish" details in release notes so let me know if that's better.

**Comment by mtekel** [comment]
Hi,

from my (operator's) point of view, I am interested if that release contains something significant - e.g. a security fix, a new feature that I can use, a breaking change etc. When I see a "final" stable release, I expect it is that kind of release. You could perhaps use dev releases on git, or not tag something "stable" until you're ready to make it a proper, significant release. That way I can know that this is dev only and I'll simply ignore it. I definitely don't want to interfere with your development process, but usually it's good practice to separate "production" (final, stable etc.) from dev - even for the consumers you are testing with.

This time, I have spent time again wondering what that release was, trying to find release notes anywhere, comparing changes in git (there were actually no changes from 3200 and even from master, making me wonder even more what's different in that release), then downloading release, verifying that this is really the release it should be, computing sha1 hashes (see https://github.com/cloudfoundry/bosh/issues/1157).... just to realize that this is only dev after your responses.

I see you have pulled that release from github, but on bosh.io, the "latest official stemcell" is still 3202...
IMO bosh.io site should also contain release notes/changelog with each release, so that I don't have to come here every time...

**Comment by dpb587** [comment]
I appreciate the more detailed release notes of v255.4 - thanks!
